/**
 * Rathisoft Themes Store — catalog data
 * Har product ka apna `icon` (image URL) aur `driveFileId` (Google Drive file ID) yahan set karein.
 */

export type StoreCategory =
  | 'shopify-theme'
  | 'wordpress-theme'
  | 'wordpress-plugin'

export type StoreFilter = 'all' | StoreCategory

export interface StoreItem {
  id: string
  name: string
  slug: string
  category: StoreCategory
  description: string
  /** Image URL (https...) ya emoji */
  icon: string
  version: string
  /** Zip size, e.g. "12.4 MB". Google Drive → file → Details se copy karein. Khali chhorne par UI Drive link dikhayega. */
  fileSize: string
  driveFileId: string
  tags: string[]
}

// ── Shopify paid themes ───────────────────────────────────────────
const SHOPIFY_THEMES: StoreItem[] = [
  {
    id: 'shopify-turbo-theme',
    name: 'Turbo (Portland)',
    slug: 'shopify-turbo-portland-theme',
    category: 'shopify-theme',
    description:
      'A premium Shopify theme known for its extreme speed and flexibility. The Portland style offers a high-end, clean aesthetic for large catalogs.',
    icon: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=640&q=80',
    version: '3.2',
    fileSize: '—',
    driveFileId: '1VoSeLLDsbKx25qYMXYysgVu5ZvIrn_zx',
    tags: ['shopify', 'speed', 'large-catalog'],
},
{
  id: 'shopify-triss-theme',
  name: 'Triss',
  slug: 'triss-shopify-theme',
  category: 'shopify-theme',
  description:
    'A specialized Shopify theme for beauty, hair extensions, and fashion stores. Features professional product layouts and mega menus.',
  icon: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1XQ2McZyRhweNXvSVCnX0MGfD-xPX0Vao',
  tags: ['shopify', 'beauty', 'fashion'],
},
{
  id: 'shopify-testament-theme',
  name: 'Testament',
  slug: 'testament-shopify-theme',
  category: 'shopify-theme',
  description:
    'Designed for high-volume stores. Testament focuses on conversion-driven features like quick view, color swatches, and sticky headers.',
  icon: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1_uWR8QICt4o6_TV8E4Kz2ayw8mHQdPUo',
  tags: ['shopify', 'high-volume', 'conversion'],
},
{
  id: 'shopify-symmetry-theme',
  name: 'Symmetry',
  slug: 'symmetry-shopify-theme',
  category: 'shopify-theme',
  description:
    'A top-rated theme for visual storytelling. Ideal for brands with high-quality photography and diverse product collections.',
  icon: 'https://images.unsplash.com/photo-1490013616775-3ca8865fb129?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8QSUyMHRvcC1yYXRlZCUyMHRoZW1lJTIwZm9yJTIwdmlzdWFsJTIwc3Rvcnl0ZWxsaW5nLiUyMElkZWFsJTIwZm9yJTIwYnJhbmRzJTIwd2l0aCUyMGhpZ2gtcXVhbGl0eSUyMHBob3RvZ3JhcGh5JTIwYW5kJTIwZGl2ZXJzZSUyMHByb2R1Y3QlMjBjb2xsZWN0aW9ucy58ZW58MHwwfDB8fHwy',
  version: '3.01',
  fileSize: '—',
  driveFileId: '18lAAZOwyehzl6yErChkGpW8rKaAOtMoU',
  tags: ['shopify', 'visual-storytelling', 'grid'],
},
{
  id: 'shopify-sunrise-theme',
  name: 'SunRise',
  slug: 'sunrise-shopify-theme',
  category: 'shopify-theme',
  description:
    'A vibrant and energetic theme perfect for toy stores, health products, or colorful fashion brands. Highly customizable sidebar.',
  icon: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1bpCfELkIvYEQoobJMXhHV6jsf1VNQcvm',
  tags: ['shopify', 'vibrant', 'retail'],
},
{
  id: 'shopify-startup-theme',
  name: 'Startup',
  slug: 'startup-shopify-theme',
  category: 'shopify-theme',
  description:
    'The ideal choice for single-product stores or small catalogs. Designed to build trust and tell a brand story on a single page.',
  icon: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1C8_x34IRJk08QqolAEgpzde1n63jpEyH',
  tags: ['shopify', 'single-product', 'clean'],
},
{
  id: 'shopify-shoptimized-theme',
  name: 'Shoptimized',
  slug: 'shoptimized-shopify-theme',
  category: 'shopify-theme',
  description:
    'A conversion-rate-optimization (CRO) focused theme. Built-in scarcity timers, social proof popups, and upsell features.',
  icon: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1hl-8FH4lnMrT9wldb4SD6a2f2FpVuNJZ',
  tags: ['shopify', 'cro', 'sales-focused'],
},
{
  id: 'shopify-turbo-portland',
  name: 'Turbo (Portland)',
  slug: 'shopify-turbo-portland-theme',
  category: 'shopify-theme',
  description:
    'High-performance Shopify theme designed for speed and large inventory stores. Features include predictive search and advanced mega menus.',
  icon: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=640&q=80',
  version: '3.2',
  fileSize: '—',
  driveFileId: '1mSDaPqUhmhzjcEWgLztSB0d1bp9ainoS',
  tags: ['shopify', 'speed', 'large-catalog'],
},
{
  id: 'shopify-icon-theme',
  name: 'Icon',
  slug: 'shopify-icon-theme',
  category: 'shopify-theme',
  description:
    'A visually driven theme perfect for brands with heavy photography. Features sticky navigation and multiple product grid options.',
  icon: 'https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=640&q=80',
  version: '1.x',
  fileSize: '—',
  driveFileId: '1brQxtdhl7xrPrA2nbQLo0ZvW3ojCZRkg',
  tags: ['shopify', 'visual-brand', 'photography'],
},
{
  id: 'shopify-retina-theme',
  name: 'Retina',
  slug: 'retina-shopify-theme',
  category: 'shopify-theme',
  description:
    'Award-winning theme for polished brands. Focuses on high-quality product imagery and sleek typography for a refined look.',
  icon: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '19oJ799s52hrPoCe83THe0ioEmSDGSX5L',
  tags: ['shopify', 'premium', 'refined'],
},
{
  id: 'shopify-responsive-theme',
  name: 'Responsive',
  slug: 'responsive-shopify-theme',
  category: 'shopify-theme',
  description:
    'A classic, sharp design that looks great on any device. Excellent for technical product displays and clear navigation.',
  icon: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1EFSNEDiu--L2jWGJoJnpr_pOnbP5hPsR',
  tags: ['shopify', 'responsive', 'clean'],
},
{
  id: 'shopify-prestige-theme',
  name: 'Prestige',
  slug: 'prestige-shopify-theme',
  category: 'shopify-theme',
  description:
    'Designed for high-end luxury brands. Focuses on high-quality storytelling and editorial-style layouts.',
  icon: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1nix-g2r4PiqYGYuPj5psheZ4VwfVB1Jp',
  tags: ['shopify', 'luxury', 'editorial'],
},
{
  id: 'shopify-pipeline-theme',
  name: 'Pipeline',
  slug: 'pipeline-shopify-theme',
  category: 'shopify-theme',
  description:
    'A minimalist theme designed for outdoorsy and lifestyle brands. Features a parallax scrolling effect and large image sections.',
  icon: 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1vjl979cN0-ezD0Pf__xbKjRUJaSIjbom',
  tags: ['shopify', 'parallax', 'minimalist'],
},
{
  id: 'shopify-mogo-theme',
  name: 'Mogo',
  slug: 'mogo-shopify-theme',
  category: 'shopify-theme',
  description:
    'A creative and multi-purpose Shopify theme with various pre-made layouts for fashion, electronics, and decor.',
  icon: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1vqoSN-VV0xHgERdl1OUkJAMTFXSXkiNE',
  tags: ['shopify', 'multipurpose', 'creative'],
},
{
  id: 'shopify-minimart-theme',
  name: 'MiniMart',
  slug: 'minimart-shopify-theme',
  category: 'shopify-theme',
  description:
    'A clean and lightweight theme tailored for small to medium shops that prioritize fast loading and mobile shopping.',
  icon: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1wnlzJ4djLoX0ike6QjhqdYE3ygYN7Hw5',
  tags: ['shopify', 'lightweight', 'small-catalog'],
},
{
  id: 'shopify-masonry-theme',
  name: 'Masonry',
  slug: 'masonry-shopify-theme',
  category: 'shopify-theme',
  description:
    'Grid-focused theme that uses a masonry layout to display products of different sizes beautifully.',
  icon: 'https://images.unsplash.com/photo-1720414574239-19b692165d47?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8R3JpZC1mb2N1c2VkJTIwdGhlbWUlMjB0aGF0JTIwdXNlcyUyMGElMjBtYXNvbnJ5JTIwbGF5b3V0JTIwdG8lMjBkaXNwbGF5JTIwcHJvZHVjdHMlMjBvZiUyMGRpZmZlcmVudCUyMHNpemVzJTIwYmVhdXRpZnVsbHkufGVufDB8MHwwfHx8Mg%3D%3D',
  version: '2018 Edition',
  fileSize: '—',
  driveFileId: '1laVPxOB4yCH2bTI-0n9qgW99COgQRuuG',
  tags: ['shopify', 'grid', 'creative'],
},
{
  id: 'shopify-launch-theme',
  name: 'Launch',
  slug: 'launch-shopify-theme',
  category: 'shopify-theme',
  description:
    'Ideal for crowdfunding and single-product launches. Built to track goals and tell your product story effectively.',
  icon: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1kAydfGtk7VdLxvpGrDP6eQAIKznFV_ow',
  tags: ['shopify', 'crowdfunding', 'single-product'],
},
{
  id: 'shopify-konversion-theme',
  name: 'Konversion',
  slug: 'konversion-shopify-theme',
  category: 'shopify-theme',
  description:
    'A performance-first Shopify theme built specifically to increase conversion rates. Includes mobile-optimized layouts and built-in sales triggers.',
  icon: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=640&q=80',
  version: '2.x',
  fileSize: '—',
  driveFileId: '17Kx_UaL5wSjU_8vPn3is5FljQHPhLOlG',
  tags: ['shopify', 'conversion', 'mobile-first'],
},
{
  id: 'shopify-kagami-theme',
  name: 'Kagami',
  slug: 'kagami-shopify-theme',
  category: 'shopify-theme',
  description:
    'Versatile theme for large catalogs. Features a unique masonry grid and integrated social media feeds to showcase your brand personality.',
  icon: 'https://images.unsplash.com/photo-1648134859177-66e35b61e106?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8VmVyc2F0aWxlJTIwdGhlbWUlMjBmb3IlMjBsYXJnZSUyMGNhdGFsb2dzLiUyMEZlYXR1cmVzJTIwYSUyMHVuaXF1ZSUyMG1hc29ucnklMjBncmlkJTIwYW5kJTIwaW50ZWdyYXRlZCUyMHNvY2lhbCUyMG1lZGlhJTIwZmVlZHMlMjB0byUyMHNob3djYXNlJTIweW91ciUyMGJyYW5kJTIwcGVyc29uYWxpdHkufGVufDB8MHwwfHx8Mg%3D%3D',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '11sphleYdGH8XL3i58ka0jMebN9eNCgIA',
  tags: ['shopify', 'grid', 'large-catalog'],
},
{
  id: 'shopify-gemini-fashion',
  name: 'Gemini Fashion',
  slug: 'gemini-fashion-shopify-theme',
  category: 'shopify-theme',
  description:
    'A stylish Shopify theme tailored for fashion and apparel brands. Includes advanced filtering and lookbook features.',
  icon: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?auto=format&fit=crop&w=640&q=80',
  version: '1.3.2',
  fileSize: '—',
  driveFileId: '1xo64uWUUnL5QfRVwzOijt3LUVRf7wvjR',
  tags: ['shopify', 'fashion', 'apparel'],
},
{
  id: 'shopify-foodly-theme',
  name: 'Foodly',
  slug: 'foodly-shopify-theme',
  category: 'shopify-theme',
  description:
    'Award-winning theme for food and grocery stores. Features a clean, organic look with focus on nutritional info and quick checkout.',
  icon: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=640&q=80',
  version: '1.8',
  fileSize: '—',
  driveFileId: '1E6SP-ovIVp1Oi0NTvpTcKAiGEKRgog4m',
  tags: ['shopify', 'grocery', 'food'],
},
{
  id: 'shopify-envy-theme',
  name: 'Envy',
  slug: 'envy-shopify-theme',
  category: 'shopify-theme',
  description:
    'Clean and professional theme ideal for stores that run frequent promotions. Includes a multi-level menu and marketing popups.',
  icon: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1kRbFV7jxln2AUufPDL4plwIknmE4rWCz',
  tags: ['shopify', 'marketing', 'clean'],
},
{
  id: 'shopify-empire-theme',
  name: 'Empire',
  slug: 'empire-shopify-theme',
  category: 'shopify-theme',
  description:
    'Amazon-style marketplace theme built for large product catalogs. Features robust search and advanced product filtering.',
  icon: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1cIi6HMYENo8rRxxhXxBjipda6TFiJicA',
  tags: ['shopify', 'marketplace', 'large-inventory'],
},
{
  id: 'shopify-ella-theme',
  name: 'Ella',
  slug: 'ella-shopify-theme',
  category: 'shopify-theme',
  description:
    'A multi-purpose Shopify theme with a focus on fashion and lifestyle. Highly customizable with numerous pre-built skins and layouts.',
  icon: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=640&q=80',
  version: '2.0.3',
  fileSize: '—',
  driveFileId: '1ZjEZW3DhvrpPDDSbFVctWKctlMzCjy53',
  tags: ['shopify', 'fashion', 'multipurpose'],
},
{
  id: 'shopify-district-theme',
  name: 'District',
  slug: 'district-shopify-theme',
  category: 'shopify-theme',
  description:
    'Perfect for showcasing featured products and collections. A great balance of visual storytelling and easy navigation.',
  icon: 'https://images.unsplash.com/photo-1556740738-b6a63e27c4df?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1hfZH2LnGM3fwoZ6onMbSARcJzamqEPAs',
  tags: ['shopify', 'featured-products', 'clean'],
},
{
  id: 'shopify-decortica-theme',
  name: 'Decortica',
  slug: 'decortica-shopify-theme',
  category: 'shopify-theme',
  description:
    'A specialized Shopify theme for home decor and furniture stores. Features elegant galleries and product spotlight sections.',
  icon: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1yH3OxNFe6x8vWN9Qffmw7HiWYDBqDemw',
  tags: ['shopify', 'decor', 'furniture'],
},
{
  id: 'shopify-booster-theme',
  name: 'Booster',
  slug: 'booster-shopify-theme',
  category: 'shopify-theme',
  description:
    'One of the fastest Shopify themes built for high conversions. Includes built-in apps like countdown timers, social proof, and upsell funnels.',
  icon: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=640&q=80',
  version: '2.2.1',
  fileSize: '—',
  driveFileId: '1pO1R_DAFn2P0rHicW4C4UwSGqltkmRhG',
  tags: ['shopify', 'conversion', 'fast'],
},
{
  id: 'shopify-basel-theme',
  name: 'Basel',
  slug: 'basel-premium-shopify-theme',
  category: 'shopify-theme',
  description:
    'A professional minimalist AJAX responsive theme. Perfect for any kind of store, from cloth and electronics to furniture and accessories.',
  icon: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1ysndeep7lBi1ncA9sU73fvdPqm8jlMiy',
  tags: ['shopify', 'ajax', 'ecommerce'],
},
{
  id: 'shopify-annabelle-theme',
  name: 'Annabelle',
  slug: 'annabelle-shopify-theme',
  category: 'shopify-theme',
  description:
    'A multi-purpose Shopify theme with a focus on feminine aesthetics. Highly customizable with unique header and footer styles.',
  icon: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=640&q=80',
  version: 'New',
  fileSize: '—',
  driveFileId: '1hbIi8RFJ2QOtnegouNEkhBwLKbPa1jnY',
  tags: ['shopify', 'feminine', 'fashion'],
},
{
  id: 'shopify-adeline-theme',
  name: 'Adeline',
  slug: 'adeline-official-shopify-theme',
  category: 'shopify-theme',
  description:
    'A clean, modern, and elegant Shopify theme. Specifically designed for fashion, jewelry, and lifestyle boutique stores.',
  icon: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=640&q=80',
  version: 'Official',
  fileSize: '—',
  driveFileId: '1qMLXUQBFlcT9ckQIBvJT3K63gIYghhrc',
  tags: ['shopify', 'boutique', 'jewelry'],
},
{
  id: 'shopify-wheels-theme',
  name: 'Wheels',
  slug: 'wheels-shopify-theme',
  category: 'shopify-theme',
  description:
    'A high-performance theme designed for automotive parts, tires, and car accessories. Features robust filtering and a technical layout.',
  icon: 'https://images.unsplash.com/photo-1649963806105-eea4bf6f5812?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8QSUyMGhpZ2gtcGVyZm9ybWFuY2UlMjB0aGVtZSUyMGRlc2lnbmVkJTIwZm9yJTIwYXV0b21vdGl2ZSUyMHBhcnRzJTJDJTIwdGlyZXMlMkMlMjBhbmQlMjBjYXIlMjBhY2Nlc3Nvcmllcy4lMjBGZWF0dXJlcyUyMHJvYnVzdCUyMGZpbHRlcmluZyUyMGFuZCUyMGElMjB0ZWNobmljYWwlMjBsYXlvdXQufGVufDB8MHwwfHx8Mg%3D%3D',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1WUUK8xsUlNrSkjzss_yEzv37Fin--OA4',
  tags: ['shopify', 'automotive', 'tires'],
},
{
  id: 'shopify-watches-theme',
  name: 'Watches',
  slug: 'watches-shopify-theme',
  category: 'shopify-theme',
  description:
    'An elegant and sophisticated theme tailored for luxury timepieces and jewelry. Highlights high-resolution product imagery and refined typography.',
  icon: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1da8oIVWh1hz7rrnu8XbUpVxpmbB3R8NZ',
  tags: ['shopify', 'luxury', 'jewelry'],
},
{
  id: 'shopify-toddler-theme',
  name: 'Toddler',
  slug: 'toddler-shopify-theme',
  category: 'shopify-theme',
  description:
    'A playful and colorful theme perfect for children’s clothing, toys, and baby accessories. Soft layouts with easy-to-navigate collections.',
  icon: 'https://images.unsplash.com/photo-1515488764276-beab7607c1e6?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1L243xhruldHXc2o9YDkLZ2x2qrUJ04He',
  tags: ['shopify', 'kids', 'toys'],
},
{
  id: 'shopify-tees-theme',
  name: 'Tees',
  slug: 'tees-shopify-theme',
  category: 'shopify-theme',
  description:
    'A streamlined theme for t-shirt brands and apparel startups. Focuses on quick product viewing and various color/size variant displays.',
  icon: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1ddE7Ypq9fxQpqHiFdrbD5IEymKsg1jUJ',
  tags: ['shopify', 'apparel', 'tshirts'],
},
{
  id: 'shopify-sports-theme',
  name: 'Sports',
  slug: 'sports-shopify-theme',
  category: 'shopify-theme',
  description:
    'Energetic and bold design for fitness gear and sports equipment. Optimized for mobile shopping and fast-loading product pages.',
  icon: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1eRWrt7R0tyYeJCBdmgnSGOR2orf3awn3',
  tags: ['shopify', 'fitness', 'sports'],
},
{
  id: 'shopify-sparkle-theme',
  name: 'Sparkle',
  slug: 'sparkle-shopify-theme',
  category: 'shopify-theme',
  description:
    'A vibrant theme for beauty products and makeup brands. Features product lookbooks and integrated social media feeds.',
  icon: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1eDJozjpGzJAuy6OZgc9K6Zf4ucCCa7Xy',
  tags: ['shopify', 'beauty', 'cosmetics'],
},
{
  id: 'shopify-skateboard-theme',
  name: 'Skateboard',
  slug: 'skateboard-shopify-theme',
  category: 'shopify-theme',
  description:
    'Edgy and modern layout for extreme sports and streetwear brands. Includes video background support and large masonry grids.',
  icon: 'https://images.unsplash.com/photo-1547447134-cd3f5c716030?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1I9Wee1mLIu7SX2JEYTqWkmMLylcIyN9H',
  tags: ['shopify', 'lifestyle', 'skating'],
},
{
  id: 'shopify-shoesnbags-theme',
  name: 'Shoes-n-bags',
  slug: 'shoes-n-bags-shopify-theme',
  category: 'shopify-theme',
  description:
    'A high-conversion theme specialized for footwear and accessories. Features advanced filtering by size, color, and material.',
  icon: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '15b4W99UmDoWYwiEqKCVWjeltfXri1yA9',
  tags: ['shopify', 'fashion', 'footwear'],
},
{
  id: 'shopify-pets-theme',
  name: 'Pets',
  slug: 'pets-shopify-theme',
  category: 'shopify-theme',
  description:
    'A warm and friendly theme designed for pet food, toys, and accessories. Includes sections for pet care tips and product categorization by animal type.',
  icon: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1F6U9Hr7kU-3mu630thRYVFM2Dp5ZosHQ',
  tags: ['shopify', 'pet-store', 'animal-care'],
},
{
  id: 'shopify-perfume-theme',
  name: 'Perfume',
  slug: 'perfume-shopify-theme',
  category: 'shopify-theme',
  description:
    'A luxurious and minimalist theme tailored for high-end fragrances and beauty products. Features elegant product displays and clean typography.',
  icon: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1znCvslVw3CFPiWZ6_w-9A3vuZ9-NQE3I',
  tags: ['shopify', 'fragrance', 'luxury'],
},
{
  id: 'shopify-organic-theme',
  name: 'Organic',
  slug: 'organic-shopify-theme',
  category: 'shopify-theme',
  description:
    'Eco-friendly and fresh design perfect for organic food, natural skincare, or herbal products. Emphasizes clean layouts and earthy tones.',
  icon: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1JBI9dCEhO-QVJCGFqTEpioIa64_71bDu',
  tags: ['shopify', 'eco-friendly', 'natural'],
},
{
  id: 'shopify-nutsnbolts-theme',
  name: 'Nuts-n-Bolts',
  slug: 'nuts-n-bolts-shopify-theme',
  category: 'shopify-theme',
  description:
    'A rugged and functional theme for hardware stores, industrial tools, and DIY supplies. Built to handle large technical catalogs with ease.',
  icon: 'https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1qUDGEYihhyXxv5VQXt7ZXrvhqCqvNGg0',
  tags: ['shopify', 'hardware', 'industrial'],
},
{
  id: 'shopify-music-theme',
  name: 'Music',
  slug: 'music-shopify-theme',
  category: 'shopify-theme',
  description:
    'A modern theme designed for musical instruments, audio gear, and vinyl records. Includes support for audio previews and rich media galleries.',
  icon: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1AckodlpYfOeHmnF-NCpkaqwbmnyP0Ce',
  tags: ['shopify', 'instruments', 'audio'],
},
{
  id: 'shopify-multistore-theme',
  name: 'Multistore',
  slug: 'multistore-shopify-theme',
  category: 'shopify-theme',
  description:
    'A versatile multi-purpose theme capable of handling diverse product categories. Ideal for general retailers and marketplace-style setups.',
  icon: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1Y6vfMcc4Mh3woUgsRq5-u6wGnpp4lazr',
  tags: ['shopify', 'multipurpose', 'marketplace'],
},
{
  id: 'shopify-lifestyle-theme',
  name: 'Lifestyle',
  slug: 'lifestyle-shopify-theme',
  category: 'shopify-theme',
  description:
    'A versatile theme for wellness and lifestyle brands. Features editorial layouts and social media integration to build a community around your products.',
  icon: 'https://images.unsplash.com/photo-1511556532299-8f660fc26c06?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '18hQnRKpjDkH1FR4j79OmTagCRFy_kDNz',
  tags: ['shopify', 'lifestyle', 'wellness'],
},
{
  id: 'shopify-kids-theme',
  name: 'Kids',
  slug: 'kids-shopify-theme',
  category: 'shopify-theme',
  description:
    'A bright and cheerful design for children’s apparel and toys. Includes easy navigation for parents and playful animation effects.',
  icon: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1cBomW4He6n_95LLAwftWQw6-dCrRwRMr',
  tags: ['shopify', 'baby', 'toys'],
},
{
  id: 'shopify-jewels-theme',
  name: 'Jewels',
  slug: 'jewels-shopify-theme',
  category: 'shopify-theme',
  description:
    'Sophisticated and high-end layout for jewelry stores. Focuses on high-detail product zoom and elegant presentation.',
  icon: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1U78-insvlBedh6xDuxDRfwgY8g5gytQn',
  tags: ['shopify', 'jewelry', 'luxury'],
},
{
  id: 'shopify-hairweave-theme',
  name: 'Hair-Weave',
  slug: 'hair-weave-shopify-theme',
  category: 'shopify-theme',
  description:
    'Specifically designed for the hair extension and wig industry. Features product comparison tables and texture filtering.',
  icon: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1vupNqVWQgTQfWxc6rA4eDHMsuqmepm4Y',
  tags: ['shopify', 'hair-extensions', 'beauty'],
},
{
  id: 'shopify-getfit-theme',
  name: 'Get-Fit',
  slug: 'get-fit-shopify-theme',
  category: 'shopify-theme',
  description:
    'A high-energy theme for fitness equipment and activewear. Built for fast performance and mobile-first shopping.',
  icon: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1aUEG7TQvWPI82AWUIB1QD14z0Q1B6hS',
  tags: ['shopify', 'fitness', 'gym'],
},
{
  id: 'shopify-furniture-theme',
  name: 'Furniture',
  slug: 'furniture-shopify-theme',
  category: 'shopify-theme',
  description:
    'Spacious layouts for interior decor and furniture stores. Features large image banners and collection-based navigation.',
  icon: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1iOIvbROFWafVhLxndwtzwqxgGpBocOF0',
  tags: ['shopify', 'interior', 'home'],
},
{
  id: 'shopify-fashion-theme',
  name: 'Fashion',
  slug: 'fashion-shopify-theme',
  category: 'shopify-theme',
  description:
    'A classic multi-purpose fashion theme. Supports diverse product types with advanced mega menus and quick-buy features.',
  icon: 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1TRxLbxHlgd2eaVyW0plSOr0fRNp-7Rju',
  tags: ['shopify', 'clothing', 'apparel'],
},
{
  id: 'shopify-electronics-theme',
  name: 'Electronics',
  slug: 'electronics-shopify-theme',
  category: 'shopify-theme',
  description:
    'Technical and clean design for gadgets and tech stores. Optimized for large catalogs and detailed specification lists.',
  icon: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '16mcPcE_TPRkglIv4cpoo9HvU1FK4HUOi',
  tags: ['shopify', 'tech', 'gadgets'],
},
{
  id: 'shopify-cosmetics-theme',
  name: 'Cosmetics',
  slug: 'cosmetics-shopify-theme',
  category: 'shopify-theme',
  description:
    'A trendy theme for makeup and skincare brands. Includes product review integration and beauty blog layouts.',
  icon: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1LVIK10obotYFTbXcRexYOCsP-nSAgGly',
  tags: ['shopify', 'makeup', 'skincare'],
},
{
  id: 'shopify-comfynight-theme',
  name: 'Comfy-Night',
  slug: 'comfy-night-shopify-theme',
  category: 'shopify-theme',
  description:
    'A cozy theme for sleepwear, bedding, and home comfort products. Focuses on soft aesthetics and customer comfort stories.',
  icon: 'https://images.unsplash.com/photo-1520263115673-610416f52ab6?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1IY04gX4u_X2lJxrtiU3G-EqXOXcQ3qRD',
  tags: ['shopify', 'sleepwear', 'home'],
},
{
  id: 'shopify-coffeeland-theme',
  name: 'Coffee-Land',
  slug: 'coffee-land-shopify-theme',
  category: 'shopify-theme',
  description:
    'A rich and warm theme designed for coffee roasters and cafes. Features include aroma-focused imagery sections and subscription model support for coffee beans.',
  icon: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1icf-SpSj3YrFNlkEgzMFwZwUOd1cMol3',
  tags: ['shopify', 'coffee', 'cafe'],
},
{
  id: 'shopify-cakeshop-theme',
  name: 'Cake-shop',
  slug: 'cake-shop-shopify-theme',
  category: 'shopify-theme',
  description:
    'A sweet and inviting layout for bakeries and confectioneries. Optimized for local delivery options and visual menus of artisanal treats.',
  icon: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1hwMUA3Bp2ifqWqe-edcCgHTLQqiAc0K8',
  tags: ['shopify', 'bakery', 'sweets'],
},
{
  id: 'shopify-boutique-theme',
  name: 'Boutique',
  slug: 'boutique-shopify-theme',
  category: 'shopify-theme',
  description:
    'A high-end, minimalist theme for designer fashion and curated collections. Focuses on storytelling and premium brand positioning.',
  icon: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1OWhSFZQhDK0daVqRryqO9V--VDM4nQ8c',
  tags: ['shopify', 'fashion', 'boutique'],
},
{
  id: 'shopify-bikini-theme',
  name: 'Bikini',
  slug: 'bikini-shopify-theme',
  category: 'shopify-theme',
  description:
    'A vibrant and summery theme for swimwear and beachwear brands. Includes support for high-impact lifestyle videos and dynamic product filters.',
  icon: 'https://images.unsplash.com/photo-1544944447-1d960854446c?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1OKEIS0x6UtUD4yRi0vjsq-HjaLBl-W9O',
  tags: ['shopify', 'swimwear', 'lifestyle'],
},
{
  id: 'shopify-appliance-theme',
  name: 'Appliance',
  slug: 'appliance-shopify-theme',
  category: 'shopify-theme',
  description:
    'A clean, structured theme for home appliances and electronics. Features detailed spec sheets and comparison tools for technical products.',
  icon: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1dXLdyDFfsb-vx6zjtlfXLXFvxqU3pKHY',
  tags: ['shopify', 'appliances', 'electronics'],
},
{
  id: 'shopify-adventure-theme',
  name: 'Adventure',
  slug: 'adventure-shopify-theme',
  category: 'shopify-theme',
  description:
    'A rugged and bold theme built for outdoor gear, travel equipment, and adventure sports. Optimized for large-scale imagery and storytelling for explorers.',
  icon: 'https://images.unsplash.com/photo-1501555088652-021faa106b9b?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '—',
  driveFileId: '1jc-F51JCprQWB5MlzSwlUsAEkDijYq1t',
  tags: ['shopify', 'outdoor', 'travel', 'equipment'],
},
  ]

// ── WordPress paid themes ─────────────────────────────────────────
const WORDPRESS_THEMES: StoreItem[] = [
  {
    id: 'quemag-magazine-theme',
    name: 'QueMag',
    slug: 'quemag-magazine-wordpress-theme',
    category: 'wordpress-theme',
    description:
      'A high-performance WordPress theme for professional bloggers and news agencies. Features clean layouts, ad spots, and SEO optimization.',
    icon: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=640&q=80',
    version: 'Latest',
    fileSize: '8.5 MB',
    driveFileId: '1H2PxL4V-OeBla4SFkKlhMK100aO7KrFi',
    tags: ['blogging', 'magazine', 'news'],
},
{
  id: 'picozo-coworking-theme',
  name: 'Picozo',
  slug: 'picozo-coworking-portfolio-theme',
  category: 'wordpress-theme',
  description:
    'Creative WordPress theme designed for coworking spaces, shared offices, and professional portfolios with Elementor support.',
  icon: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '14.6 MB',
  driveFileId: '1MOciNknaEXdIKJKfP3Y2DgvXn575uaTJ',
  tags: ['portfolio', 'coworking', 'elementor'],
},
{
  id: 'wp-blissful-theme',
  name: 'Blissful',
  slug: 'blissful-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A versatile and elegant WordPress theme designed for lifestyle bloggers and creative entrepreneurs. Focuses on typography and white space.',
  icon: 'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.1 MB',
  driveFileId: '1Tssd5vmq8yZK-8zs5O3nZ6NED1tDIeEV',
  tags: ['lifestyle', 'blogging', 'clean'],
},
{
  id: 'wp-breakthrough-pro',
  name: 'Breakthrough Pro',
  slug: 'breakthrough-pro-theme',
  category: 'wordpress-theme',
  description:
    'A bold and modern theme for marketing and advertising agencies. Combines sleek colors with a professional business layout.',
  icon: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.4 MB',
  driveFileId: '1k2b2KLla385UB3lFzDqY12DkncNp5C4M',
  tags: ['agency', 'marketing', 'genesis'],
},
{
  id: 'wp-business-pro',
  name: 'Business Pro',
  slug: 'business-pro-theme',
  category: 'wordpress-theme',
  description:
    'The ultimate corporate WordPress theme. Features a flexible front-page layout and full integration with the block editor.',
  icon: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.8 MB',
  driveFileId: '1GDLMwJNNqQJQTrUhAtyCsRv2yU37wCeW',
  tags: ['business', 'corporate', 'professional'],
},
{
  id: 'wp-cookd-pro',
  name: 'Cook’d',
  slug: 'cookd-pro-theme',
  category: 'wordpress-theme',
  description:
    'A food-focused WordPress theme with a super clean look. Designed to showcase large, high-quality food photography and recipes.',
  icon: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=640&q=80',
  version: '1.1.0',
  fileSize: '1.9 MB',
  driveFileId: '1yaXU1vVeTdoj6qBXW2coIjyBpOrX4CBs',
  tags: ['food', 'recipes', 'minimalist'],
},
{
  id: 'wp-dear-theme',
  name: 'Dear',
  slug: 'dear-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A charming and personalized theme for personal stories, journaling, and elegant blogging experiences.',
  icon: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.5 MB',
  driveFileId: '1LxNwCg3JfGhzjz6NOoN4hlkc-XyQFiAs',
  tags: ['journal', 'personal-blog', 'typography'],
},
{
  id: 'wp-decor-theme',
  name: 'Decor',
  slug: 'decor-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'Perfect for interior designers and home decor enthusiasts. This theme emphasizes visual portfolios and style galleries.',
  icon: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.5 MB',
  driveFileId: '1FVBja7w4TjUzmQtY_RxnGGqOCVBPfNVj',
  tags: ['interior-design', 'portfolio', 'decor'],
},
{
  id: 'wp-divine-theme',
  name: 'Divine',
  slug: 'divine-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A multi-purpose Genesis child theme with a focus on feminine style and organized content layouts.',
  icon: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.3 MB',
  driveFileId: '1ltWemFlpXEY4tLgApXaDGJXpO-RnHm-2',
  tags: ['feminine', 'blogging', 'versatile'],
},
{
  id: 'wp-elegance-theme',
  name: 'Elegance',
  slug: 'elegance-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A sophisticated and high-end theme for luxury brands and high-fashion blogs. Includes premium layout options.',
  icon: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.1 MB',
  driveFileId: '15NbSi1q1fiS_9NzvLMpZxeH4Pk8r4Mok',
  tags: ['luxury', 'fashion', 'premium'],
},
{
  id: 'wp-eleven40-pro',
  name: 'Eleven40 Pro',
  slug: 'eleven40-pro-theme',
  category: 'wordpress-theme',
  description:
    'A wide, content-first theme that captures the attention of readers. Built on the Genesis Framework for speed and security.',
  icon: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.0 MB',
  driveFileId: '1gRjGkZuU6TPWa9_WFckroDNzgvBcnQoN',
  tags: ['content-focused', 'blog', 'genesis'],
},
{
  id: 'wp-enterprise-pro',
  name: 'Enterprise Pro',
  slug: 'enterprise-pro-theme',
  category: 'wordpress-theme',
  description:
    'Take charge of your corporate image with this sharp, clean, and fast-loading theme for established businesses.',
  icon: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.6 MB',
  driveFileId: '1SOxwWZtQ1vkQupdLS6AlVDSx8qCMqX-l',
  tags: ['corporate', 'enterprise', 'modern'],
},
{
  id: 'wp-essence-pro',
  name: 'Essence Pro',
  slug: 'essence-pro-theme',
  category: 'wordpress-theme',
  description:
    'A beautiful, clutter-free theme designed for health, wellness, and lifestyle niches. Focuses on relaxation and clarity.',
  icon: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.0 MB',
  driveFileId: '1zho6JTwuypLeVdVMJ5pC7CrHj4YYtxI_',
  tags: ['wellness', 'lifestyle', 'minimalist'],
},
{
  id: 'wp-executive-pro',
  name: 'Executive Pro',
  slug: 'executive-pro-theme',
  category: 'wordpress-theme',
  description:
    'Designed for high-level executives and corporate leaders to showcase their vision and portfolio with a professional edge.',
  icon: 'https://images.unsplash.com/photo-1454165833767-027ffea9e772?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.4 MB',
  driveFileId: '1ixcrW61wMX36DLd9GgUG0Lj2e3TG1rud',
  tags: ['corporate', 'leadership', 'genesis'],
},
{
  id: 'wp-focus-pro',
  name: 'Focus Pro',
  slug: 'focus-pro-theme',
  category: 'wordpress-theme',
  description:
    'A minimalist theme that brings your content to the center stage. Perfect for writers and bloggers who value readability.',
  icon: 'https://images.unsplash.com/photo-1473186533642-42419a06f13b?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.8 MB',
  driveFileId: '1IHLShIg2c0iiVZN1so12zotGHGKc4WXZ',
  tags: ['minimalist', 'blogging', 'readability'],
},
{
  id: 'wp-foodie-pro',
  name: 'Foodie Pro',
  slug: 'foodie-pro-theme',
  category: 'wordpress-theme',
  description:
    'The world’s most popular food blogging theme. Sleek, clean, and packed with widget areas for recipe showcases.',
  icon: 'https://images.unsplash.com/photo-1495521821757-a1efb6729352?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.2 MB',
  driveFileId: '19Ndo-ql0B6gXTjG_5JlcZbFRDWC72Kw_',
  tags: ['food', 'recipes', 'popular'],
},
{
  id: 'wp-gallery-pro',
  name: 'Gallery Pro',
  slug: 'gallery-pro-theme',
  category: 'wordpress-theme',
  description:
    'A stunning visual theme for photographers and artists. Features a gorgeous gallery layout to display high-res work.',
  icon: 'https://images.unsplash.com/photo-1452421822248-d4c2b47f0c81?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.9 MB',
  driveFileId: '11NV0k4ss0NmtIg9r_MYzV9EhIwlcRz5d',
  tags: ['photography', 'portfolio', 'visual'],
},
{
  id: 'wp-generate-pro',
  name: 'Generate Pro',
  slug: 'generate-pro-theme',
  category: 'wordpress-theme',
  description:
    'Focused on lead generation and email list building. Includes high-converting opt-in sections directly on the home page.',
  icon: 'https://images.unsplash.com/photo-1557838923-2985c318be48?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.1 MB',
  driveFileId: '1owM8TEubdStgP2BiBR2cc56ekBYP7d2H',
  tags: ['marketing', 'leads', 'conversion'],
},
{
  id: 'wp-genesis-framework',
  name: 'Genesis Framework & Sample',
  slug: 'genesis-framework-sample',
  category: 'wordpress-theme',
  description:
    'The foundational framework for WordPress. Fast, secure, and SEO-optimized, including the standard Sample child theme.',
  icon: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=640&q=80',
  version: '2.6.1',
  fileSize: '1.2 MB',
  driveFileId: '1bJv0r_j1xXSqCXSqEIvlu8b1LAQekNYe',
  tags: ['framework', 'seo', 'core'],
},
{
  id: 'wp-glam-pro',
  name: 'Glam Pro',
  slug: 'glam-pro-theme',
  category: 'wordpress-theme',
  description:
    'A chic and stylish theme for beauty and fashion influencers. Offers a clean, polished look for aesthetic-heavy blogs.',
  icon: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.7 MB',
  driveFileId: '113M-l_wpM7jAOJ7ZiauEs-3c9JDKH5rf',
  tags: ['beauty', 'fashion', 'influencer'],
},
{
  id: 'wp-interior-pro',
  name: 'Interior Pro',
  slug: 'interior-pro-theme',
  category: 'wordpress-theme',
  description:
    'Tailored for interior designers and decorators. Focuses on spatial layout and large imagery to showcase home projects.',
  icon: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.5 MB',
  driveFileId: '1rHe2QfKdeZGZwoF1qztz6UPDCRJ1-5lK',
  tags: ['interior', 'design', 'home'],
},
{
  id: 'wp-jessica-theme',
  name: 'Jessica',
  slug: 'jessica-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'An e-commerce ready theme designed specifically for feminine brands and boutique online stores.',
  icon: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.8 MB',
  driveFileId: '1UimkS3YLyE6ZQ413YvGEHFt18CaKdLiU',
  tags: ['ecommerce', 'boutique', 'feminine'],
},
{
  id: 'wp-kickstart-pro',
  name: 'Kickstart Pro',
  slug: 'kickstart-pro-theme',
  category: 'wordpress-theme',
  description:
    'High-energy theme for startups and new ventures. Bold elements designed to get your brand moving fast.',
  icon: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.0 MB',
  driveFileId: '1npOqDVUoHKgDWuW6Gg9wnI9Zxd7HvfDJ',
  tags: ['startup', 'business', 'bold'],
},
{
  id: 'wp-lifestyle-pro',
  name: 'Lifestyle Pro',
  slug: 'lifestyle-pro-theme',
  category: 'wordpress-theme',
  description:
    'A flexible and bright layout for diverse content. Great for magazines that cover anything from health to travel.',
  icon: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.2 MB',
  driveFileId: '1SdNaGfwaY7URoKNbXEQMmP9SLD_ZH2kG',
  tags: ['lifestyle', 'magazine', 'travel'],
},
{
  id: 'wp-luscious-theme',
  name: 'Luscious',
  slug: 'luscious-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A bold and colorful theme for personal brands that want to stand out with a "pop" of personality.',
  icon: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.9 MB',
  driveFileId: '11o0V0BwHVfTqw601HJE4NfRmWAsPBvfw',
  tags: ['colorful', 'branding', 'creative'],
},
{
  id: 'wp-magazine-pro',
  name: 'Magazine Pro',
  slug: 'magazine-pro-theme',
  category: 'wordpress-theme',
  description:
    'The gold standard for online publishers. Professional grid layout that makes any site look like a high-end news source.',
  icon: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.6 MB',
  driveFileId: '1Vx9MzpmaB5GzmbRlGtUpmJxFgF0jib03',
  tags: ['news', 'magazine', 'grid'],
},
{
  id: 'wp-mai-pro-series',
  name: 'Mai Pro Series',
  slug: 'mai-pro-wordpress-themes',
  category: 'wordpress-theme',
  description:
    'Highly customizable and feature-rich themes for professional services like law firms or broad lifestyle platforms.',
  icon: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '4.5 MB',
  driveFileId: '17JMCHQKJqwxb4-px-iaN1mvUcsLKDz8t',
  tags: ['legal', 'professional', 'lifestyle'],
},
{
  id: 'wp-maker-pro',
  name: 'Maker Pro',
  slug: 'maker-pro-theme',
  category: 'wordpress-theme',
  description:
    'A theme for creators. Whether you make art, furniture, or code, Maker Pro puts your creations front and center.',
  icon: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.3 MB',
  driveFileId: '1g9EVvRv0IyrJWeKl25j0-XjQOYyZMoiN',
  tags: ['maker', 'creative', 'portfolio'],
},
{
  id: 'wp-market-theme',
  name: 'Market',
  slug: 'market-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A flexible e-commerce theme designed to showcase products clearly and drive sales. Perfect for small to medium online shops.',
  icon: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.4 MB',
  driveFileId: '1PPMVYScZccVscwug87aT3P7RV3iVpzjC',
  tags: ['ecommerce', 'shop', 'business'],
},
{
  id: 'wp-metric-theme',
  name: 'Metric',
  slug: 'metric-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A sleek, tech-focused theme with a dark aesthetic. Ideal for software developers, tech reviewers, and gaming blogs.',
  icon: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.9 MB',
  driveFileId: '1j_Jq8mHHFyvWoKw9n6TPkSxVT_pJc7AD',
  tags: ['tech', 'dark-mode', 'blogging'],
},
{
  id: 'wp-milan-pro',
  name: 'Milan Pro',
  slug: 'milan-pro-theme',
  category: 'wordpress-theme',
  description:
    'High-fashion magazine theme that brings Italian elegance to your blog. Features sophisticated typography and layout.',
  icon: 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.8 MB',
  driveFileId: '1Gsc0QbCBqARL5HEqIujuC-rOtjTAaPX3',
  tags: ['fashion', 'magazine', 'luxury'],
},
{
  id: 'wp-modern-portfolio-pro',
  name: 'Modern Portfolio Pro',
  slug: 'modern-portfolio-pro-theme',
  category: 'wordpress-theme',
  description:
    'A clean, professional way to showcase your best work. Features a stark, high-contrast design that makes images pop.',
  icon: 'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.1 MB',
  driveFileId: '16OL2qUOomCpTwnuBxbPESf17gQMZNL4h',
  tags: ['portfolio', 'minimalist', 'clean'],
},
{
  id: 'wp-news-pro',
  name: 'News Pro',
  slug: 'news-pro-theme',
  category: 'wordpress-theme',
  description:
    'Built for heavy-content sites. It supports multiple navigation areas and a clean grid for daily news updates.',
  icon: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.5 MB',
  driveFileId: '1gxMiINF-kD5Cg1QxbutN9BIEgk0NsQ_K',
  tags: ['news', 'magazine', 'content'],
},
{
  id: 'wp-outreach-pro',
  name: 'Outreach Pro',
  slug: 'outreach-pro-theme',
  category: 'wordpress-theme',
  description:
    'A theme designed specifically for non-profits and community organizations to share their message effectively.',
  icon: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.3 MB',
  driveFileId: '1tB1pGrWJRjoX3g2pYrCeHWbh_Gy_0X7B',
  tags: ['non-profit', 'community', 'clean'],
},
{
  id: 'wp-parallax-pro',
  name: 'Parallax Pro',
  slug: 'parallax-pro-theme',
  category: 'wordpress-theme',
  description:
    'Keeps your content in proper narrative order. Stunning parallax scrolling effects for a modern vertical storytelling experience.',
  icon: 'https://images.unsplash.com/photo-1461747541859-407a66952c00?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.1 MB',
  driveFileId: '1RY-cGbm3anWPvVuU6X0SUGtpJ1wRlhLM',
  tags: ['parallax', 'storytelling', 'modern'],
},
{
  id: 'wp-pretty-chic',
  name: 'Pretty Chic',
  slug: 'pretty-chic-themes',
  category: 'wordpress-theme',
  description:
    'Stylish and feminine themes designed for creative entrepreneurs. Includes versatile widget areas and beautiful ad placements.',
  icon: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '4.2 MB',
  driveFileId: '1VR-uBmc90RUmShAt_ckmMUCa1cdIE5j3',
  tags: ['feminine', 'entrepreneur', 'style'],
},
{
    id: 'wp-pretty-creative',
    name: 'Pretty Creative',
    slug: 'pretty-creative-themes',
    category: 'wordpress-theme',
    description:
      'Stylish and feminine themes designed for creative entrepreneurs. Includes versatile widget areas and beautiful ad placements.',
    icon: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=640&q=80',
    version: 'Latest',
    fileSize: '4.2 MB',
    driveFileId: '1Q6-I1UJRHwly-q6g_H8701CIc1X98tRS',
    tags: ['feminine', 'entrepreneur', 'style'],
},
{
  id: 'wp-showcase-pro',
  name: 'Showcase Pro',
  slug: 'showcase-pro-theme',
  category: 'wordpress-theme',
  description:
    'A bright and clean theme to display your products or services. Ideal for agencies and high-end portfolios.',
  icon: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.9 MB',
  driveFileId: '16sQgMpl7H_O7lRe3A2g3opu77hWFydl5',
  tags: ['showcase', 'agency', 'clean'],
},
{
  id: 'wp-spi-pro',
  name: 'Smart Passive Income Pro',
  slug: 'smart-passive-income-pro-theme',
  category: 'wordpress-theme',
  description:
    'Designed with Pat Flynn, this theme focuses on three key pillars: design, content, and strategy for online business growth.',
  icon: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.7 MB',
  driveFileId: '1y_nFG_Ku0MQI2oABaXRG-6jL-wI4vic9',
  tags: ['business', 'growth', 'marketing'],
},
{
  id: 'wp-refined-theme',
  name: 'Refined',
  slug: 'refined-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A timeless and classic theme for entrepreneurs. Focuses on branding and high-quality photography for a premium feel.',
  icon: 'https://images.unsplash.com/photo-1491336477066-31156b5e4f35?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.6 MB',
  driveFileId: '1iB5v8kkLBdZsoVW47pX5wL1hL-FMBcOl',
  tags: ['classic', 'branding', 'entrepreneur'],
},
{
  id: 'wp-slush-pro',
  name: 'Slush Pro',
  slug: 'slush-pro-theme',
  category: 'wordpress-theme',
  description:
    'A catchy, marketing-focused theme with a unique sidebar layout and beautiful typography for personal brands.',
  icon: 'https://images.unsplash.com/photo-1493612276216-ee3925520721?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.4 MB',
  driveFileId: '1QaRRc-SKOTzwkZqfoE_Vcs8MuQUOH_mK',
  tags: ['personal-brand', 'creative', 'blog'],
},
{
  id: 'wp-mindstream-theme',
  name: 'Mindstream',
  slug: 'mindstream-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A multi-post format theme that makes it easy to share images, videos, quotes, and links. Perfect for micro-blogging.',
  icon: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.7 MB',
  driveFileId: '1GXxB096elU11VCqregEaOvGTkyYLFksP',
  tags: ['microblogging', 'post-formats', 'genesis'],
},
{
  id: 'wp-nitrous-theme',
  name: 'Nitrous',
  slug: 'nitrous-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A lightweight, high-performance theme built for speed. Its clean design is ideal for tech and performance-focused blogs.',
  icon: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.5 MB',
  driveFileId: '1G2LTLdM3L8JxtfAeuA2vvPhjFLaMQP7F',
  tags: ['speed', 'performance', 'minimalist'],
},
{
  id: 'wp-platinum-theme',
  name: 'Platinum',
  slug: 'platinum-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A premium corporate theme with a sophisticated grayscale palette. Designed for established businesses and consultants.',
  icon: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.3 MB',
  driveFileId: '1uQnlAUEyCYB4BsnW90AlwjiBdvBYnj_8',
  tags: ['corporate', 'consulting', 'business'],
},
{
  id: 'wp-prose-theme',
  name: 'Prose',
  slug: 'prose-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'The ultimate "point and click" customizable theme. Allows users to change colors and fonts without touching a single line of code.',
  icon: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.0 MB',
  driveFileId: '1VlK-8I-rzZvF7iuVZJAUxeFvEFHdkUjL',
  tags: ['customizable', 'user-friendly', 'blog'],
},
{
  id: 'wp-simply-pro',
  name: 'Simply Pro',
  slug: 'simply-pro-theme',
  category: 'wordpress-theme',
  description:
    'A minimalist theme that follows the "less is more" philosophy. Beautifully simple layouts for lifestyle and personal blogs.',
  icon: 'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.1 MB',
  driveFileId: '1Q9lxbisMkEUQcOUS4EuCzIaaGxly4PCB',
  tags: ['minimalist', 'lifestyle', 'clean'],
},
{
  id: 'wp-studio-pro',
  name: 'Studio Pro',
  slug: 'studio-pro-theme',
  category: 'wordpress-theme',
  description:
    'The perfect choice for creative agencies and studios. Features bold imagery and smooth animations to showcase your portfolio.',
  icon: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.5 MB',
  driveFileId: '1LR54EkkGR6wB8Aykrddek7ic-qFTLIro',
  tags: ['agency', 'studio', 'portfolio'],
},
{
  id: 'wp-wellness-pro',
  name: 'Wellness Pro',
  slug: 'wellness-pro-theme',
  category: 'wordpress-theme',
  description:
    'Specifically designed for the health and wellness industry. Focuses on mindful layouts and calming color schemes.',
  icon: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.9 MB',
  driveFileId: '1h7eRIU2hC03LiykVvpOeQx8j4g1atFlF',
  tags: ['health', 'wellness', 'yoga'],
},
{
  id: 'wp-wintersong-pro',
  name: 'Wintersong Pro',
  slug: 'wintersong-pro-theme',
  category: 'wordpress-theme',
  description:
    'A unique, condensed theme that packs a lot of punch in a small space. Ideal for solo bloggers with a focused message.',
  icon: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.8 MB',
  driveFileId: '1PVC7q6T84TLRGOwf4o_GmDKokvFEbBVT',
  tags: ['condensed', 'personal', 'sidebar-layout'],
},
{
  id: 'wp-whitespace-pro',
  name: 'Whitespace Pro',
  slug: 'whitespace-pro-theme',
  category: 'wordpress-theme',
  description:
    'Uses negative space to highlight your content. A favorite for modern writers who want a distraction-free experience.',
  icon: 'https://images.unsplash.com/photo-1483054941562-f03cb932c446?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.9 MB',
  driveFileId: '1aJh6sLA6aUPNe--y8wc4hiK2HDZWfRke',
  tags: ['whitespace', 'minimalist', 'writing'],
},
{
  id: 'wp-the-411-pro',
  name: 'The 411 Pro',
  slug: 'the-411-pro-theme',
  category: 'wordpress-theme',
  description:
    'A clean, professional theme designed to get your most important information to your audience. Ideal for news-style blogging and personal brands.',
  icon: 'https://images.unsplash.com/photo-1495024894617-1dfc5dff819c?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.1 MB',
  driveFileId: '13eKTXARf17H_scfnYugOip4GiXHt_xMB',
  tags: ['news', 'minimalist', 'genesis'],
},
{
  id: 'wp-venture-theme',
  name: 'Venture',
  slug: 'venture-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A professional business theme with a bold design. Perfect for startups and agencies looking to showcase their portfolio and expertise.',
  icon: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.5 MB',
  driveFileId: '1QE8eqVFx8D--cGhiDPldbi_mNhf48-BK',
  tags: ['business', 'agency', 'startup'],
},




]

// ── WordPress paid plugins ────────────────────────────────────────
const WORDPRESS_PLUGINS: StoreItem[] = [
  {
    id: 'wp-facebook-feed-plugin',
    name: 'Facebook Feed Plugin',
    slug: 'wordpress-facebook-feed-plugin',
    category: 'wordpress-plugin',
    description:
      'Easily display your Facebook posts, photos, and videos directly on your WordPress site. Seamlessly integrate your social media presence with your website content.',
    icon: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=640&q=80',
    version: '2022.02.21',
    fileSize: '2.8 MB',
    driveFileId: '1GliKJvD5OPmm2nX5Ahqdggerd3zmOe4O',
    tags: ['plugin', 'facebook', 'social-feed'],
},
{
  id: 'wp-pinterest-feed-plugin',
  name: 'Pinterest Feed Plugin',
  slug: 'wordpress-pinterest-feed-plugin',
  category: 'wordpress-plugin',
  description:
    'Showcase your Pinterest boards and pins on your WordPress website. A perfect tool for bloggers and brands to highlight their visual inspirations.',
  icon: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?auto=format&fit=crop&w=640&q=80',
  version: '2022.02.21',
  fileSize: '2.5 MB',
  driveFileId: '1RukouJGTJHjN9uHztMbwDiTCXVLmP-jy',
  tags: ['plugin', 'pinterest', 'visual-marketing'],
},
  {
    id: 'wp-digits-plugin',
    name: 'Digits',
    slug: 'digits-wordpress-login-plugin',
    category: 'wordpress-plugin',
    description:
      'The most powerful WordPress login and signup plugin. Allows users to register and login with their mobile number using OTP (SMS). No more passwords needed.',
    icon: 'https://images.unsplash.com/photo-1556745753-b2904692b3cd?auto=format&fit=crop&w=640&q=80',
    version: '7.4.1.2',
    fileSize: '12.4 MB',
    driveFileId: '1VBB481GaLiNtJs75okjsqnlY5vheVSQl',
    tags: ['wordpress', 'otp-login', 'sms-verification'],
  },
  {
    id: 'laralink-url-shortener',
    name: 'Laralink',
    slug: 'laralink-url-shortener-script',
    category: 'wordpress-plugin',
    description:
      'A powerful URL shortener script to create, manage, and track short links. Features include bio-link pages, QR code generation, and advanced analytics.',
    icon: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=640&q=80',
    version: 'Latest',
    fileSize: '15.8 MB',
    driveFileId: '1VBB481GaLiNtJs75okjsqnlY5vheVSQl',
    tags: ['url-shortener', 'marketing', 'link-tracking'],
},
{
  id: 'woocommerce-attach-me',
  name: 'WooCommerce Attach Me',
  slug: 'woocommerce-attach-me-plugin',
  category: 'wordpress-plugin',
  description:
    'Powerful document management plugin for WooCommerce. Attach manuals, warranties, or digital files directly to orders and products for customers.',
  icon: 'https://images.unsplash.com/photo-1614850523296-d8c1af93d400?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '4.2 MB',
  driveFileId: '1KCsIv604u05d34HISKBWVbu6v0iiqrBM',
  tags: ['woocommerce', 'attachments', 'order-management'],
},
{
  id: 'products-scheduler-restrict',
  name: 'Products Scheduler',
  slug: 'products-scheduler-restrict-access',
  category: 'wordpress-plugin',
  description:
    'Take control of your product visibility. Schedule when products go live or restrict access based on user roles and membership levels.',
  icon: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.1 MB',
  driveFileId: '1NcwqbSZy4UBfxPe_LNAUuLJy3mJKGD90',
  tags: ['woocommerce', 'scheduling', 'restriction'],
},
{
  id: 'premium-seo-pack',
  name: 'Premium SEO Pack',
  slug: 'premium-seo-pack-wordpress-plugin',
  category: 'wordpress-plugin',
  description:
    'A complete SEO solution for WordPress. Includes on-page optimization, sitemaps, backlink tracking, and social sharing tools.',
  icon: 'https://images.unsplash.com/photo-1432888622747-4eb9a8f2c20e?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '11.2 MB',
  driveFileId: '1PAQMz8nDm7dPiyUzCmnu1UybcrXfiREA',
  tags: ['seo', 'marketing', 'optimization'],
},
{
  id: 'wp-zuper-radio-player',
  name: 'Zuper Radio Player',
  slug: 'zuper-shoutcast-icecast-radio-player',
  category: 'wordpress-plugin',
  description:
    'A professional Shoutcast and Icecast radio player for WordPress. Features include stream history, current song display, and artist images.',
  icon: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.5 MB',
  driveFileId: '1jLXUBykjxurew1OqqbgKavKN4hwamNQZ',
  tags: ['plugin', 'radio', 'shoutcast', 'audio'],
} ,
{
  id: 'wp-yt-vimeo-slider',
  name: 'Youtube Vimeo Video Player',
  slug: 'youtube-vimeo-video-player-slider-wp',
  category: 'wordpress-plugin',
  description:
    'A versatile slider and player for YouTube and Vimeo videos. Supports playlists, touch swipe, and multiple layout options.',
  icon: 'https://images.unsplash.com/photo-1524169358666-79f22534bc6e?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '4.2 MB',
  driveFileId: '169v8cG4f7Hmu1VaehXy5If_E4am2Rh0Q',
  tags: ['plugin', 'video', 'slider', 'youtube'],
},
{
  id: 'wp-xpromoter-topbar',
  name: 'xPromoter',
  slug: 'xpromoter-top-bar-switcher-wp',
  category: 'wordpress-plugin',
  description:
    'A responsive top bar plugin to display promotions, announcements, or notifications. Includes a unique switcher for multiple messages.',
  icon: 'https://images.unsplash.com/photo-1502355984994-812f711096ac?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.8 MB',
  driveFileId: '1GNKSCKFo6SyU7uVq0u-7DUbxLpET8AID',
  tags: ['plugin', 'marketing', 'notification-bar'],
},
{
  id: 'wp-logos-showcase',
  name: 'Logos Showcase',
  slug: 'wordpress-logos-showcase-grid-carousel',
  category: 'wordpress-plugin',
  description:
    'Display a list of clients, supporters, or partners logos in a clean grid or an automated carousel layout.',
  icon: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.4 MB',
  driveFileId: '1QS_gSSIPzfmVI50_L6UPncs00SD-eGUo',
  tags: ['plugin', 'logos', 'carousel', 'branding'],
},
{
  id: 'wp-fullscreen-video-bg',
  name: 'Video Player & BG',
  slug: 'video-player-fullscreen-background-wp',
  category: 'wordpress-plugin',
  description:
    'Create stunning full-screen video backgrounds for your website pages or specific sections with this powerful player.',
  icon: 'https://images.unsplash.com/photo-1492619339714-8c8397e6388a?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '5.1 MB',
  driveFileId: '1OZ6DZEOCBRdB0reNhdhVJstgXE4iGu5Q',
  tags: ['plugin', 'video-background', 'full-screen'],
},
{
  id: 'wp-universal-video-player',
  name: 'Universal Video Player',
  slug: 'universal-video-player-wp',
  category: 'wordpress-plugin',
  description:
    'A top-tier video player that supports self-hosted MP4, YouTube, and Vimeo with a customizable interface and skins.',
  icon: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '4.8 MB',
  driveFileId: '10BiA96jnFMQyBiDOxrRTPtWd9Y7qBh60',
  tags: ['plugin', 'video', 'html5', 'custom-player'],
},
{
  id: 'wp-uberslider-layer',
  name: 'UberSlider',
  slug: 'uberslider-layer-slider-wp',
  category: 'wordpress-plugin',
  description:
    'A multi-layer slider plugin allowing you to add text, images, and buttons over sliding backgrounds with custom animations.',
  icon: 'https://images.unsplash.com/photo-1454165833767-027ffea9e772?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '6.2 MB',
  driveFileId: '1cq7mrCcWQAal8o70n4KmTzyAbAjSqFLe',
  tags: ['plugin', 'slider', 'layers', 'animations'],
},
{
  id: 'wp-sticky-music-player',
  name: 'Sticky Music Player',
  slug: 'sticky-html5-music-player-wp',
  category: 'wordpress-plugin',
  description:
    'An audio player that stays fixed at the top or bottom of your page, providing continuous playback as users browse.',
  icon: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.9 MB',
  driveFileId: '1hDCJWYo1RHAGSvBfxS_i5lOSxMfnHnLQ',
  tags: ['plugin', 'audio', 'sticky', 'music'],
},
{
  id: 'wp-revolution-video-player',
  name: 'Revolution Video Player',
  slug: 'revolution-video-player-bottom-playlist',
  category: 'wordpress-plugin',
  description:
    'Feature-rich video player with a bottom-scrollable playlist. Supports advertisements and social sharing options.',
  icon: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '5.5 MB',
  driveFileId: '1RzXnF_EEMWPRsQIFhABupxnHQOO3x3c4',
  tags: ['plugin', 'video', 'playlist', 'marketing'],
},
{
  id: 'wp-zoom-slider',
  name: 'Zoom Slider',
  slug: 'responsive-zoom-in-out-slider-wp',
  category: 'wordpress-plugin',
  description:
    'A beautiful slider plugin that applies Ken Burns style zoom effects to your images for a cinematic feel.',
  icon: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.1 MB',
  driveFileId: '1Vk5ntvX01JeJnKm6XTAPCWz-pV9L-nZn',
  tags: ['plugin', 'slider', 'ken-burns', 'visual'],
},
{
  id: 'wp-audio-player-pro',
  name: 'Audio Player PRO',
  slug: 'responsive-html5-audio-player-pro-wp',
  category: 'wordpress-plugin',
  description:
    'A professional-grade audio player with custom skins, playlist support, and full mobile responsiveness.',
  icon: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.7 MB',
  driveFileId: '1KEw8OK4oNHBIYOVaDhwix4MgpWCWjIbD',
  tags: ['plugin', 'audio', 'pro', 'playlist'],
},
{
  id: 'wp-shoutcast-radio-player',
  name: 'Radio Player PRO',
  slug: 'radio-player-shoutcast-icecast-wp',
  category: 'wordpress-plugin',
  description:
    'High-performance radio player specifically optimized for Shoutcast and Icecast servers with metadata support.',
  icon: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.8 MB',
  driveFileId: '1Fipdt365Y9grIag_AviCvrb3qLZBFTfi',
  tags: ['plugin', 'radio', 'streaming', 'shoutcast'],
},
{
  id: 'wp-multimedia-carousel',
  name: 'Multimedia Carousel',
  slug: 'multimedia-responsive-carousel-wp',
  category: 'wordpress-plugin',
  description:
    'An all-in-one carousel that supports images, videos (YouTube/Vimeo), and HTML content in a 3D or flat layout.',
  icon: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '4.3 MB',
  driveFileId: '1Y0tvEP0DzMb8XcQVBkSHuV9RAKau6mr6',
  tags: ['plugin', 'carousel', 'multimedia', '3d'],
},
{
  id: 'wp-magic-slider',
  name: 'Magic Slider',
  slug: 'magic-responsive-slider-carousel-wp',
  category: 'wordpress-plugin',
  description:
    'A creative slider and carousel plugin with over 100 transition effects and multiple navigation styles.',
  icon: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.9 MB',
  driveFileId: '1i-frCSHImI8cSV6kEvVdyixD_AJxd9sV',
  tags: ['plugin', 'slider', 'carousel', 'effects'],
},
{
  id: 'wp-magic-xmas-card',
  name: 'Magic Christmas Card',
  slug: 'magic-christmas-card-animation',
  category: 'wordpress-plugin',
  description:
    'Add a festive touch to your site with an animated Christmas card. Features falling snow and holiday music.',
  icon: 'https://images.unsplash.com/photo-1543589077-47d81606c1ad?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.5 MB',
  driveFileId: '1zMM98_1zomUkt9VF1wxYIjuSVly7toni',
  tags: ['plugin', 'holiday', 'animation', 'christmas'],
},
{
  id: 'wp-infinito-css',
  name: 'INFINITO',
  slug: 'infinito-custom-css-wp',
  category: 'wordpress-plugin',
  description:
    'Easily inject custom CSS into specific pages, posts, or your entire website without modifying theme files.',
  icon: 'https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.2 MB',
  driveFileId: '1uVdhgODKdeGhkE-Z7_EtQzOslbj7z2xE',
  tags: ['plugin', 'css', 'development', 'customization'],
},
{
  id: 'wp-fullscreen-bg-pro',
  name: 'FullScreen Background',
  slug: 'image-video-fullscreen-background-wp',
  category: 'wordpress-plugin',
  description:
    'A professional plugin for setting high-res images or videos as full-screen backgrounds with overlay support.',
  icon: 'https://images.unsplash.com/photo-1493612276216-ee3925520721?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.3 MB',
  driveFileId: '1tt7AKiZo2Mvym1Q6AHPvadCvbIyAfqw7',
  tags: ['plugin', 'background', 'design', 'video'],
},
{
  id: 'wp-html5-video-player',
  name: 'HTML5 Video Player',
  slug: 'html5-video-player-wordpress-plugin',
  category: 'wordpress-plugin',
  description:
    'A simple yet powerful HTML5 player for self-hosted videos. Highly compatible with all modern browsers.',
  icon: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.1 MB',
  driveFileId: '1Wi7jlMT8tYTBOB8ZCT-rkaxdurtWdSXr',
  tags: ['plugin', 'video', 'html5', 'player'],
},
{
  id: 'wp-html5-audio-player',
  name: 'HTML5 Audio Player',
  slug: 'html5-audio-player-wordpress-plugin',
  category: 'wordpress-plugin',
  description:
    'A lightweight and responsive audio player for MP3 and OGG files. Easy to embed using shortcodes.',
  icon: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.7 MB',
  driveFileId: '1vLE_cbudwnObmN-IyW4N4WVW1CbphPxi',
  tags: ['plugin', 'audio', 'music', 'player'],
},
{
  id: 'wp-famous-grid',
  name: 'Famous Gallery',
  slug: 'famous-responsive-grid-gallery-wp',
  category: 'wordpress-plugin',
  description:
    'Create a stunning grid of images and videos. Features a lightbox, social sharing, and infinite scroll options.',
  icon: 'https://images.unsplash.com/photo-1554147090-e11d63561a51?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.6 MB',
  driveFileId: '18XKBNd4faeyg9K9rTCQzcQQ-vN4wesdW',
  tags: ['plugin', 'gallery', 'grid', 'video'],
},
{
  id: 'wp-eventozilla',
  name: 'EventoZilla',
  slug: 'eventozilla-event-calendar-wp',
  category: 'wordpress-plugin',
  description:
    'Manage and display your events in a beautiful calendar view. Includes event categories and details pages.',
  icon: 'https://images.unsplash.com/photo-1506784365847-bbad939e9335?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '4.5 MB',
  driveFileId: '1Z5NsWA-B1FgOs48hsGjflbqBHO1Y7_F_',
  tags: ['plugin', 'events', 'calendar', 'management'],
},
{
  id: 'wp-countdown-pro',
  name: 'CountDown Pro',
  slug: 'countdown-pro-wp-plugin',
  category: 'wordpress-plugin',
  description:
    'Add stylish countdown timers to your site. Perfect for product launches, sales, or event announcements.',
  icon: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.9 MB',
  driveFileId: '1lKvoj1Av4KdiGAf_zsDDGNWuGTJfC-VZ',
  tags: ['plugin', 'timer', 'marketing', 'sales'],
},
{
  id: 'wp-clever-radio',
  name: 'CLEVER Radio',
  slug: 'clever-html5-radio-player-history',
  category: 'wordpress-plugin',
  description:
    'A smart radio player for Shoutcast/Icecast with automatic stream reconnection and detailed song history.',
  icon: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.2 MB',
  driveFileId: '1OscRe3kaA3Vxy9Bu9aC7S6DC1DObuYBB',
  tags: ['plugin', 'radio', 'shoutcast', 'history'],
},
{
  id: 'wp-chronos-countdown',
  name: 'Chronos CountDown',
  slug: 'chronos-countdown-wp',
  category: 'wordpress-plugin',
  description:
    'A highly customizable countdown timer with multiple themes and an integrated flip-clock animation style.',
  icon: 'https://images.unsplash.com/photo-1516733725897-1aa73b87c8e8?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.3 MB',
  driveFileId: '10hwBGjL8430E02BeU94879gcqM3lC7k8',
  tags: ['plugin', 'timer', 'countdown', 'clock'],
},
{
  id: 'wp-apollo-player',
  name: 'Apollo',
  slug: 'apollo-sticky-fullwidth-audio-player',
  category: 'wordpress-plugin',
  description:
    'A full-width sticky audio player with a sleek, minimalist design and seamless stream switching.',
  icon: 'https://images.unsplash.com/photo-1510915228340-29c85a43dcfe?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.4 MB',
  driveFileId: '1v70Pa-pB0lVoT8-IO86wkbPZdGgXU4Lt',
  tags: ['plugin', 'audio', 'sticky', 'player'],
},
{
  id: 'wp-all-in-one-slider',
  name: 'All In One Slider',
  slug: 'all-in-one-slider-responsive-wp',
  category: 'wordpress-plugin',
  description:
    'A complete slider solution featuring thumbnails, banners, and carousels with multiple transition effects.',
  icon: 'https://images.unsplash.com/photo-1481487196290-c152efe083f5?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '4.7 MB',
  driveFileId: '1MvNLuUS4Fb7xuUmNsrwam2kablGsBfS9',
  tags: ['plugin', 'slider', 'banner', 'responsive'],
},
{
  id: 'wp-accordion-slider-pro',
  name: 'Accordion Slider PRO',
  slug: 'accordion-slider-pro-responsive-wp',
  category: 'wordpress-plugin',
  description:
    'A unique accordion-style slider for images and videos that expands sections on hover or click.',
  icon: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.6 MB',
  driveFileId: '1Aa2ZSlz0ieTzWmYn6yOLJgke7qQ6-Z5o',
  tags: ['plugin', 'slider', 'accordion', 'video'],
},




]

/** Full catalog (Shopify themes + WP themes + WP plugins) */
export const STORE_ITEMS: StoreItem[] = [
  ...SHOPIFY_THEMES,
  ...WORDPRESS_THEMES,
  ...WORDPRESS_PLUGINS,
]

export function countByCategory(items: StoreItem[]) {
  return {
    shopify: items.filter((i) => i.category === 'shopify-theme').length,
    wpThemes: items.filter((i) => i.category === 'wordpress-theme').length,
    wpPlugins: items.filter((i) => i.category === 'wordpress-plugin').length,
  }
}

export function isIconImageUrl(icon: string): boolean {
  return icon.startsWith('http://') || icon.startsWith('https://')
}
