/**
 * Rathisoft Themes Store — catalog data
 * Har product ka apna `icon` (image URL) aur `driveFileId` (Google Drive file ID) yahan set karein.
 */

export type StoreCategory =
  | 'shopify-theme'
  | 'wordpress-theme'
  | 'wordpress-plugin'

export type StoreFilter = 'all' | StoreCategory

export interface StoreItem {
  id: string
  name: string
  slug: string
  category: StoreCategory
  description: string
  /** Image URL (https...) ya emoji */
  icon: string
  version: string
  /** Zip size, e.g. "12.4 MB". Google Drive → file → Details se copy karein. Khali chhorne par UI Drive link dikhayega. */
  fileSize: string
  driveFileId: string
  tags: string[]
}

// ── Shopify paid themes ───────────────────────────────────────────
const SHOPIFY_THEMES: StoreItem[] = [
  
  
  
  //Properly added themes are added above
  {
    id: 'shopify-impulse',
    name: 'Impulse',
    slug: 'shopify-impulse-theme',
    category: 'shopify-theme',
    description:
      'High-converting Shopify theme for fashion & lifestyle brands. Promotional sections, homepage stories, and mobile-first layouts.',
    icon: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=640&q=80',
    version: '8.x',
    /** Google Drive: 53344000 bytes (page embed metadata) */
    fileSize: '50.9 MB',
    driveFileId: '1aeeJM2M2IDRckW3lJUDesDotUgATY_5B',
    tags: ['shopify', 'fashion', 'conversion'],
  },
  {
    id: 'shopify-prestige',
    name: 'Prestige',
    slug: 'shopify-prestige-theme',
    category: 'shopify-theme',
    description:
      'Luxury-focused Shopify theme with editorial layouts, lookbooks, and refined typography for premium brands.',
    icon: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=640&q=80',
    version: '7.x',
    fileSize: '',
    driveFileId: 'YOUR_SHOPIFY_PRESTIGE_DRIVE_FILE_ID',
    tags: ['shopify', 'luxury', 'editorial'],
  },
  {
    id: 'shopify-dawn-premium',
    name: 'Dawn Extended Pack',
    slug: 'shopify-dawn-extended-theme',
    category: 'shopify-theme',
    description:
      'Enhanced Shopify Online Store 2.0 theme package with extra sections, presets, and performance tweaks.',
    icon: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=640&q=80',
    version: 'OS 2.0',
    fileSize: '',
    driveFileId: 'YOUR_SHOPIFY_DAWN_PACK_DRIVE_FILE_ID',
    tags: ['shopify', 'os2', 'sections'],
  },
]

// ── WordPress paid themes ─────────────────────────────────────────
const WORDPRESS_THEMES: StoreItem[] = [
  {
    id: 'quemag-magazine-theme',
    name: 'QueMag',
    slug: 'quemag-magazine-wordpress-theme',
    category: 'wordpress-theme',
    description:
      'A high-performance WordPress theme for professional bloggers and news agencies. Features clean layouts, ad spots, and SEO optimization.',
    icon: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=640&q=80',
    version: 'Latest',
    fileSize: '8.5 MB',
    driveFileId: '1H2PxL4V-OeBla4SFkKlhMK100aO7KrFi',
    tags: ['blogging', 'magazine', 'news'],
},
{
  id: 'picozo-coworking-theme',
  name: 'Picozo',
  slug: 'picozo-coworking-portfolio-theme',
  category: 'wordpress-theme',
  description:
    'Creative WordPress theme designed for coworking spaces, shared offices, and professional portfolios with Elementor support.',
  icon: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '14.6 MB',
  driveFileId: '1MOciNknaEXdIKJKfP3Y2DgvXn575uaTJ',
  tags: ['portfolio', 'coworking', 'elementor'],
},
{
  id: 'wp-blissful-theme',
  name: 'Blissful',
  slug: 'blissful-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A versatile and elegant WordPress theme designed for lifestyle bloggers and creative entrepreneurs. Focuses on typography and white space.',
  icon: 'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.1 MB',
  driveFileId: '1Tssd5vmq8yZK-8zs5O3nZ6NED1tDIeEV',
  tags: ['lifestyle', 'blogging', 'clean'],
},
{
  id: 'wp-breakthrough-pro',
  name: 'Breakthrough Pro',
  slug: 'breakthrough-pro-theme',
  category: 'wordpress-theme',
  description:
    'A bold and modern theme for marketing and advertising agencies. Combines sleek colors with a professional business layout.',
  icon: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.4 MB',
  driveFileId: '1k2b2KLla385UB3lFzDqY12DkncNp5C4M',
  tags: ['agency', 'marketing', 'genesis'],
},
{
  id: 'wp-business-pro',
  name: 'Business Pro',
  slug: 'business-pro-theme',
  category: 'wordpress-theme',
  description:
    'The ultimate corporate WordPress theme. Features a flexible front-page layout and full integration with the block editor.',
  icon: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.8 MB',
  driveFileId: '1GDLMwJNNqQJQTrUhAtyCsRv2yU37wCeW',
  tags: ['business', 'corporate', 'professional'],
},
{
  id: 'wp-cookd-pro',
  name: 'Cook’d',
  slug: 'cookd-pro-theme',
  category: 'wordpress-theme',
  description:
    'A food-focused WordPress theme with a super clean look. Designed to showcase large, high-quality food photography and recipes.',
  icon: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=640&q=80',
  version: '1.1.0',
  fileSize: '1.9 MB',
  driveFileId: '1yaXU1vVeTdoj6qBXW2coIjyBpOrX4CBs',
  tags: ['food', 'recipes', 'minimalist'],
},
{
  id: 'wp-dear-theme',
  name: 'Dear',
  slug: 'dear-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A charming and personalized theme for personal stories, journaling, and elegant blogging experiences.',
  icon: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.5 MB',
  driveFileId: '1LxNwCg3JfGhzjz6NOoN4hlkc-XyQFiAs',
  tags: ['journal', 'personal-blog', 'typography'],
},
{
  id: 'wp-decor-theme',
  name: 'Decor',
  slug: 'decor-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'Perfect for interior designers and home decor enthusiasts. This theme emphasizes visual portfolios and style galleries.',
  icon: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.5 MB',
  driveFileId: '1FVBja7w4TjUzmQtY_RxnGGqOCVBPfNVj',
  tags: ['interior-design', 'portfolio', 'decor'],
},
{
  id: 'wp-divine-theme',
  name: 'Divine',
  slug: 'divine-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A multi-purpose Genesis child theme with a focus on feminine style and organized content layouts.',
  icon: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.3 MB',
  driveFileId: '1ltWemFlpXEY4tLgApXaDGJXpO-RnHm-2',
  tags: ['feminine', 'blogging', 'versatile'],
},
{
  id: 'wp-elegance-theme',
  name: 'Elegance',
  slug: 'elegance-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A sophisticated and high-end theme for luxury brands and high-fashion blogs. Includes premium layout options.',
  icon: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.1 MB',
  driveFileId: '15NbSi1q1fiS_9NzvLMpZxeH4Pk8r4Mok',
  tags: ['luxury', 'fashion', 'premium'],
},
{
  id: 'wp-eleven40-pro',
  name: 'Eleven40 Pro',
  slug: 'eleven40-pro-theme',
  category: 'wordpress-theme',
  description:
    'A wide, content-first theme that captures the attention of readers. Built on the Genesis Framework for speed and security.',
  icon: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.0 MB',
  driveFileId: '1gRjGkZuU6TPWa9_WFckroDNzgvBcnQoN',
  tags: ['content-focused', 'blog', 'genesis'],
},
{
  id: 'wp-enterprise-pro',
  name: 'Enterprise Pro',
  slug: 'enterprise-pro-theme',
  category: 'wordpress-theme',
  description:
    'Take charge of your corporate image with this sharp, clean, and fast-loading theme for established businesses.',
  icon: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.6 MB',
  driveFileId: '1SOxwWZtQ1vkQupdLS6AlVDSx8qCMqX-l',
  tags: ['corporate', 'enterprise', 'modern'],
},
{
  id: 'wp-essence-pro',
  name: 'Essence Pro',
  slug: 'essence-pro-theme',
  category: 'wordpress-theme',
  description:
    'A beautiful, clutter-free theme designed for health, wellness, and lifestyle niches. Focuses on relaxation and clarity.',
  icon: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.0 MB',
  driveFileId: '1zho6JTwuypLeVdVMJ5pC7CrHj4YYtxI_',
  tags: ['wellness', 'lifestyle', 'minimalist'],
},
{
  id: 'wp-executive-pro',
  name: 'Executive Pro',
  slug: 'executive-pro-theme',
  category: 'wordpress-theme',
  description:
    'Designed for high-level executives and corporate leaders to showcase their vision and portfolio with a professional edge.',
  icon: 'https://images.unsplash.com/photo-1454165833767-027ffea9e772?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.4 MB',
  driveFileId: '1ixcrW61wMX36DLd9GgUG0Lj2e3TG1rud',
  tags: ['corporate', 'leadership', 'genesis'],
},
{
  id: 'wp-focus-pro',
  name: 'Focus Pro',
  slug: 'focus-pro-theme',
  category: 'wordpress-theme',
  description:
    'A minimalist theme that brings your content to the center stage. Perfect for writers and bloggers who value readability.',
  icon: 'https://images.unsplash.com/photo-1473186533642-42419a06f13b?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.8 MB',
  driveFileId: '1IHLShIg2c0iiVZN1so12zotGHGKc4WXZ',
  tags: ['minimalist', 'blogging', 'readability'],
},
{
  id: 'wp-foodie-pro',
  name: 'Foodie Pro',
  slug: 'foodie-pro-theme',
  category: 'wordpress-theme',
  description:
    'The world’s most popular food blogging theme. Sleek, clean, and packed with widget areas for recipe showcases.',
  icon: 'https://images.unsplash.com/photo-1495521821757-a1efb6729352?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.2 MB',
  driveFileId: '19Ndo-ql0B6gXTjG_5JlcZbFRDWC72Kw_',
  tags: ['food', 'recipes', 'popular'],
},
{
  id: 'wp-gallery-pro',
  name: 'Gallery Pro',
  slug: 'gallery-pro-theme',
  category: 'wordpress-theme',
  description:
    'A stunning visual theme for photographers and artists. Features a gorgeous gallery layout to display high-res work.',
  icon: 'https://images.unsplash.com/photo-1452421822248-d4c2b47f0c81?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.9 MB',
  driveFileId: '11NV0k4ss0NmtIg9r_MYzV9EhIwlcRz5d',
  tags: ['photography', 'portfolio', 'visual'],
},
{
  id: 'wp-generate-pro',
  name: 'Generate Pro',
  slug: 'generate-pro-theme',
  category: 'wordpress-theme',
  description:
    'Focused on lead generation and email list building. Includes high-converting opt-in sections directly on the home page.',
  icon: 'https://images.unsplash.com/photo-1557838923-2985c318be48?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.1 MB',
  driveFileId: '1owM8TEubdStgP2BiBR2cc56ekBYP7d2H',
  tags: ['marketing', 'leads', 'conversion'],
},
{
  id: 'wp-genesis-framework',
  name: 'Genesis Framework & Sample',
  slug: 'genesis-framework-sample',
  category: 'wordpress-theme',
  description:
    'The foundational framework for WordPress. Fast, secure, and SEO-optimized, including the standard Sample child theme.',
  icon: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=640&q=80',
  version: '2.6.1',
  fileSize: '1.2 MB',
  driveFileId: '1bJv0r_j1xXSqCXSqEIvlu8b1LAQekNYe',
  tags: ['framework', 'seo', 'core'],
},
{
  id: 'wp-glam-pro',
  name: 'Glam Pro',
  slug: 'glam-pro-theme',
  category: 'wordpress-theme',
  description:
    'A chic and stylish theme for beauty and fashion influencers. Offers a clean, polished look for aesthetic-heavy blogs.',
  icon: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.7 MB',
  driveFileId: '113M-l_wpM7jAOJ7ZiauEs-3c9JDKH5rf',
  tags: ['beauty', 'fashion', 'influencer'],
},
{
  id: 'wp-interior-pro',
  name: 'Interior Pro',
  slug: 'interior-pro-theme',
  category: 'wordpress-theme',
  description:
    'Tailored for interior designers and decorators. Focuses on spatial layout and large imagery to showcase home projects.',
  icon: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.5 MB',
  driveFileId: '1rHe2QfKdeZGZwoF1qztz6UPDCRJ1-5lK',
  tags: ['interior', 'design', 'home'],
},
{
  id: 'wp-jessica-theme',
  name: 'Jessica',
  slug: 'jessica-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'An e-commerce ready theme designed specifically for feminine brands and boutique online stores.',
  icon: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.8 MB',
  driveFileId: '1UimkS3YLyE6ZQ413YvGEHFt18CaKdLiU',
  tags: ['ecommerce', 'boutique', 'feminine'],
},
{
  id: 'wp-kickstart-pro',
  name: 'Kickstart Pro',
  slug: 'kickstart-pro-theme',
  category: 'wordpress-theme',
  description:
    'High-energy theme for startups and new ventures. Bold elements designed to get your brand moving fast.',
  icon: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.0 MB',
  driveFileId: '1npOqDVUoHKgDWuW6Gg9wnI9Zxd7HvfDJ',
  tags: ['startup', 'business', 'bold'],
},
{
  id: 'wp-lifestyle-pro',
  name: 'Lifestyle Pro',
  slug: 'lifestyle-pro-theme',
  category: 'wordpress-theme',
  description:
    'A flexible and bright layout for diverse content. Great for magazines that cover anything from health to travel.',
  icon: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.2 MB',
  driveFileId: '1SdNaGfwaY7URoKNbXEQMmP9SLD_ZH2kG',
  tags: ['lifestyle', 'magazine', 'travel'],
},
{
  id: 'wp-luscious-theme',
  name: 'Luscious',
  slug: 'luscious-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A bold and colorful theme for personal brands that want to stand out with a "pop" of personality.',
  icon: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.9 MB',
  driveFileId: '11o0V0BwHVfTqw601HJE4NfRmWAsPBvfw',
  tags: ['colorful', 'branding', 'creative'],
},
{
  id: 'wp-magazine-pro',
  name: 'Magazine Pro',
  slug: 'magazine-pro-theme',
  category: 'wordpress-theme',
  description:
    'The gold standard for online publishers. Professional grid layout that makes any site look like a high-end news source.',
  icon: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.6 MB',
  driveFileId: '1Vx9MzpmaB5GzmbRlGtUpmJxFgF0jib03',
  tags: ['news', 'magazine', 'grid'],
},
{
  id: 'wp-mai-pro-series',
  name: 'Mai Pro Series',
  slug: 'mai-pro-wordpress-themes',
  category: 'wordpress-theme',
  description:
    'Highly customizable and feature-rich themes for professional services like law firms or broad lifestyle platforms.',
  icon: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '4.5 MB',
  driveFileId: '17JMCHQKJqwxb4-px-iaN1mvUcsLKDz8t',
  tags: ['legal', 'professional', 'lifestyle'],
},
{
  id: 'wp-maker-pro',
  name: 'Maker Pro',
  slug: 'maker-pro-theme',
  category: 'wordpress-theme',
  description:
    'A theme for creators. Whether you make art, furniture, or code, Maker Pro puts your creations front and center.',
  icon: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.3 MB',
  driveFileId: '1g9EVvRv0IyrJWeKl25j0-XjQOYyZMoiN',
  tags: ['maker', 'creative', 'portfolio'],
},
{
  id: 'wp-market-theme',
  name: 'Market',
  slug: 'market-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A flexible e-commerce theme designed to showcase products clearly and drive sales. Perfect for small to medium online shops.',
  icon: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.4 MB',
  driveFileId: '1PPMVYScZccVscwug87aT3P7RV3iVpzjC',
  tags: ['ecommerce', 'shop', 'business'],
},
{
  id: 'wp-metric-theme',
  name: 'Metric',
  slug: 'metric-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A sleek, tech-focused theme with a dark aesthetic. Ideal for software developers, tech reviewers, and gaming blogs.',
  icon: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.9 MB',
  driveFileId: '1j_Jq8mHHFyvWoKw9n6TPkSxVT_pJc7AD',
  tags: ['tech', 'dark-mode', 'blogging'],
},
{
  id: 'wp-milan-pro',
  name: 'Milan Pro',
  slug: 'milan-pro-theme',
  category: 'wordpress-theme',
  description:
    'High-fashion magazine theme that brings Italian elegance to your blog. Features sophisticated typography and layout.',
  icon: 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.8 MB',
  driveFileId: '1Gsc0QbCBqARL5HEqIujuC-rOtjTAaPX3',
  tags: ['fashion', 'magazine', 'luxury'],
},
{
  id: 'wp-modern-portfolio-pro',
  name: 'Modern Portfolio Pro',
  slug: 'modern-portfolio-pro-theme',
  category: 'wordpress-theme',
  description:
    'A clean, professional way to showcase your best work. Features a stark, high-contrast design that makes images pop.',
  icon: 'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.1 MB',
  driveFileId: '16OL2qUOomCpTwnuBxbPESf17gQMZNL4h',
  tags: ['portfolio', 'minimalist', 'clean'],
},
{
  id: 'wp-news-pro',
  name: 'News Pro',
  slug: 'news-pro-theme',
  category: 'wordpress-theme',
  description:
    'Built for heavy-content sites. It supports multiple navigation areas and a clean grid for daily news updates.',
  icon: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.5 MB',
  driveFileId: '1gxMiINF-kD5Cg1QxbutN9BIEgk0NsQ_K',
  tags: ['news', 'magazine', 'content'],
},
{
  id: 'wp-outreach-pro',
  name: 'Outreach Pro',
  slug: 'outreach-pro-theme',
  category: 'wordpress-theme',
  description:
    'A theme designed specifically for non-profits and community organizations to share their message effectively.',
  icon: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.3 MB',
  driveFileId: '1tB1pGrWJRjoX3g2pYrCeHWbh_Gy_0X7B',
  tags: ['non-profit', 'community', 'clean'],
},
{
  id: 'wp-parallax-pro',
  name: 'Parallax Pro',
  slug: 'parallax-pro-theme',
  category: 'wordpress-theme',
  description:
    'Keeps your content in proper narrative order. Stunning parallax scrolling effects for a modern vertical storytelling experience.',
  icon: 'https://images.unsplash.com/photo-1461747541859-407a66952c00?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.1 MB',
  driveFileId: '1RY-cGbm3anWPvVuU6X0SUGtpJ1wRlhLM',
  tags: ['parallax', 'storytelling', 'modern'],
},
{
  id: 'wp-pretty-chic',
  name: 'Pretty Chic',
  slug: 'pretty-chic-themes',
  category: 'wordpress-theme',
  description:
    'Stylish and feminine themes designed for creative entrepreneurs. Includes versatile widget areas and beautiful ad placements.',
  icon: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '4.2 MB',
  driveFileId: '1VR-uBmc90RUmShAt_ckmMUCa1cdIE5j3',
  tags: ['feminine', 'entrepreneur', 'style'],
},
{
    id: 'wp-pretty-creative',
    name: 'Pretty Creative',
    slug: 'pretty-creative-themes',
    category: 'wordpress-theme',
    description:
      'Stylish and feminine themes designed for creative entrepreneurs. Includes versatile widget areas and beautiful ad placements.',
    icon: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=640&q=80',
    version: 'Latest',
    fileSize: '4.2 MB',
    driveFileId: '1Q6-I1UJRHwly-q6g_H8701CIc1X98tRS',
    tags: ['feminine', 'entrepreneur', 'style'],
},
{
  id: 'wp-showcase-pro',
  name: 'Showcase Pro',
  slug: 'showcase-pro-theme',
  category: 'wordpress-theme',
  description:
    'A bright and clean theme to display your products or services. Ideal for agencies and high-end portfolios.',
  icon: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.9 MB',
  driveFileId: '16sQgMpl7H_O7lRe3A2g3opu77hWFydl5',
  tags: ['showcase', 'agency', 'clean'],
},
{
  id: 'wp-spi-pro',
  name: 'Smart Passive Income Pro',
  slug: 'smart-passive-income-pro-theme',
  category: 'wordpress-theme',
  description:
    'Designed with Pat Flynn, this theme focuses on three key pillars: design, content, and strategy for online business growth.',
  icon: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.7 MB',
  driveFileId: '1y_nFG_Ku0MQI2oABaXRG-6jL-wI4vic9',
  tags: ['business', 'growth', 'marketing'],
},
{
  id: 'wp-refined-theme',
  name: 'Refined',
  slug: 'refined-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A timeless and classic theme for entrepreneurs. Focuses on branding and high-quality photography for a premium feel.',
  icon: 'https://images.unsplash.com/photo-1491336477066-31156b5e4f35?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.6 MB',
  driveFileId: '1iB5v8kkLBdZsoVW47pX5wL1hL-FMBcOl',
  tags: ['classic', 'branding', 'entrepreneur'],
},
{
  id: 'wp-slush-pro',
  name: 'Slush Pro',
  slug: 'slush-pro-theme',
  category: 'wordpress-theme',
  description:
    'A catchy, marketing-focused theme with a unique sidebar layout and beautiful typography for personal brands.',
  icon: 'https://images.unsplash.com/photo-1493612276216-ee3925520721?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.4 MB',
  driveFileId: '1QaRRc-SKOTzwkZqfoE_Vcs8MuQUOH_mK',
  tags: ['personal-brand', 'creative', 'blog'],
},
{
  id: 'wp-mindstream-theme',
  name: 'Mindstream',
  slug: 'mindstream-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A multi-post format theme that makes it easy to share images, videos, quotes, and links. Perfect for micro-blogging.',
  icon: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.7 MB',
  driveFileId: '1GXxB096elU11VCqregEaOvGTkyYLFksP',
  tags: ['microblogging', 'post-formats', 'genesis'],
},
{
  id: 'wp-nitrous-theme',
  name: 'Nitrous',
  slug: 'nitrous-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A lightweight, high-performance theme built for speed. Its clean design is ideal for tech and performance-focused blogs.',
  icon: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.5 MB',
  driveFileId: '1G2LTLdM3L8JxtfAeuA2vvPhjFLaMQP7F',
  tags: ['speed', 'performance', 'minimalist'],
},
{
  id: 'wp-platinum-theme',
  name: 'Platinum',
  slug: 'platinum-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A premium corporate theme with a sophisticated grayscale palette. Designed for established businesses and consultants.',
  icon: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.3 MB',
  driveFileId: '1uQnlAUEyCYB4BsnW90AlwjiBdvBYnj_8',
  tags: ['corporate', 'consulting', 'business'],
},
{
  id: 'wp-prose-theme',
  name: 'Prose',
  slug: 'prose-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'The ultimate "point and click" customizable theme. Allows users to change colors and fonts without touching a single line of code.',
  icon: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.0 MB',
  driveFileId: '1VlK-8I-rzZvF7iuVZJAUxeFvEFHdkUjL',
  tags: ['customizable', 'user-friendly', 'blog'],
},
{
  id: 'wp-simply-pro',
  name: 'Simply Pro',
  slug: 'simply-pro-theme',
  category: 'wordpress-theme',
  description:
    'A minimalist theme that follows the "less is more" philosophy. Beautifully simple layouts for lifestyle and personal blogs.',
  icon: 'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.1 MB',
  driveFileId: '1Q9lxbisMkEUQcOUS4EuCzIaaGxly4PCB',
  tags: ['minimalist', 'lifestyle', 'clean'],
},
{
  id: 'wp-studio-pro',
  name: 'Studio Pro',
  slug: 'studio-pro-theme',
  category: 'wordpress-theme',
  description:
    'The perfect choice for creative agencies and studios. Features bold imagery and smooth animations to showcase your portfolio.',
  icon: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.5 MB',
  driveFileId: '1LR54EkkGR6wB8Aykrddek7ic-qFTLIro',
  tags: ['agency', 'studio', 'portfolio'],
},
{
  id: 'wp-wellness-pro',
  name: 'Wellness Pro',
  slug: 'wellness-pro-theme',
  category: 'wordpress-theme',
  description:
    'Specifically designed for the health and wellness industry. Focuses on mindful layouts and calming color schemes.',
  icon: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.9 MB',
  driveFileId: '1h7eRIU2hC03LiykVvpOeQx8j4g1atFlF',
  tags: ['health', 'wellness', 'yoga'],
},
{
  id: 'wp-wintersong-pro',
  name: 'Wintersong Pro',
  slug: 'wintersong-pro-theme',
  category: 'wordpress-theme',
  description:
    'A unique, condensed theme that packs a lot of punch in a small space. Ideal for solo bloggers with a focused message.',
  icon: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.8 MB',
  driveFileId: '1PVC7q6T84TLRGOwf4o_GmDKokvFEbBVT',
  tags: ['condensed', 'personal', 'sidebar-layout'],
},
{
  id: 'wp-whitespace-pro',
  name: 'Whitespace Pro',
  slug: 'whitespace-pro-theme',
  category: 'wordpress-theme',
  description:
    'Uses negative space to highlight your content. A favorite for modern writers who want a distraction-free experience.',
  icon: 'https://images.unsplash.com/photo-1483054941562-f03cb932c446?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.9 MB',
  driveFileId: '1aJh6sLA6aUPNe--y8wc4hiK2HDZWfRke',
  tags: ['whitespace', 'minimalist', 'writing'],
},
{
  id: 'wp-the-411-pro',
  name: 'The 411 Pro',
  slug: 'the-411-pro-theme',
  category: 'wordpress-theme',
  description:
    'A clean, professional theme designed to get your most important information to your audience. Ideal for news-style blogging and personal brands.',
  icon: 'https://images.unsplash.com/photo-1495024894617-1dfc5dff819c?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.1 MB',
  driveFileId: '13eKTXARf17H_scfnYugOip4GiXHt_xMB',
  tags: ['news', 'minimalist', 'genesis'],
},
{
  id: 'wp-venture-theme',
  name: 'Venture',
  slug: 'venture-wordpress-theme',
  category: 'wordpress-theme',
  description:
    'A professional business theme with a bold design. Perfect for startups and agencies looking to showcase their portfolio and expertise.',
  icon: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.5 MB',
  driveFileId: '1QE8eqVFx8D--cGhiDPldbi_mNhf48-BK',
  tags: ['business', 'agency', 'startup'],
},




]

// ── WordPress paid plugins ────────────────────────────────────────
const WORDPRESS_PLUGINS: StoreItem[] = [
  {
    id: 'wp-facebook-feed-plugin',
    name: 'Facebook Feed Plugin',
    slug: 'wordpress-facebook-feed-plugin',
    category: 'wordpress-plugin',
    description:
      'Easily display your Facebook posts, photos, and videos directly on your WordPress site. Seamlessly integrate your social media presence with your website content.',
    icon: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=640&q=80',
    version: '2022.02.21',
    fileSize: '2.8 MB',
    driveFileId: '1GliKJvD5OPmm2nX5Ahqdggerd3zmOe4O',
    tags: ['plugin', 'facebook', 'social-feed'],
},
{
  id: 'wp-pinterest-feed-plugin',
  name: 'Pinterest Feed Plugin',
  slug: 'wordpress-pinterest-feed-plugin',
  category: 'wordpress-plugin',
  description:
    'Showcase your Pinterest boards and pins on your WordPress website. A perfect tool for bloggers and brands to highlight their visual inspirations.',
  icon: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?auto=format&fit=crop&w=640&q=80',
  version: '2022.02.21',
  fileSize: '2.5 MB',
  driveFileId: '1RukouJGTJHjN9uHztMbwDiTCXVLmP-jy',
  tags: ['plugin', 'pinterest', 'visual-marketing'],
},
  {
    id: 'wp-digits-plugin',
    name: 'Digits',
    slug: 'digits-wordpress-login-plugin',
    category: 'wordpress-plugin',
    description:
      'The most powerful WordPress login and signup plugin. Allows users to register and login with their mobile number using OTP (SMS). No more passwords needed.',
    icon: 'https://images.unsplash.com/photo-1556745753-b2904692b3cd?auto=format&fit=crop&w=640&q=80',
    version: '7.4.1.2',
    fileSize: '12.4 MB',
    driveFileId: '1VBB481GaLiNtJs75okjsqnlY5vheVSQl',
    tags: ['wordpress', 'otp-login', 'sms-verification'],
  },
  {
    id: 'laralink-url-shortener',
    name: 'Laralink',
    slug: 'laralink-url-shortener-script',
    category: 'wordpress-plugin',
    description:
      'A powerful URL shortener script to create, manage, and track short links. Features include bio-link pages, QR code generation, and advanced analytics.',
    icon: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=640&q=80',
    version: 'Latest',
    fileSize: '15.8 MB',
    driveFileId: '1VBB481GaLiNtJs75okjsqnlY5vheVSQl',
    tags: ['url-shortener', 'marketing', 'link-tracking'],
},
{
  id: 'woocommerce-attach-me',
  name: 'WooCommerce Attach Me',
  slug: 'woocommerce-attach-me-plugin',
  category: 'wordpress-plugin',
  description:
    'Powerful document management plugin for WooCommerce. Attach manuals, warranties, or digital files directly to orders and products for customers.',
  icon: 'https://images.unsplash.com/photo-1614850523296-d8c1af93d400?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '4.2 MB',
  driveFileId: '1KCsIv604u05d34HISKBWVbu6v0iiqrBM',
  tags: ['woocommerce', 'attachments', 'order-management'],
},
{
  id: 'products-scheduler-restrict',
  name: 'Products Scheduler',
  slug: 'products-scheduler-restrict-access',
  category: 'wordpress-plugin',
  description:
    'Take control of your product visibility. Schedule when products go live or restrict access based on user roles and membership levels.',
  icon: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.1 MB',
  driveFileId: '1NcwqbSZy4UBfxPe_LNAUuLJy3mJKGD90',
  tags: ['woocommerce', 'scheduling', 'restriction'],
},
{
  id: 'premium-seo-pack',
  name: 'Premium SEO Pack',
  slug: 'premium-seo-pack-wordpress-plugin',
  category: 'wordpress-plugin',
  description:
    'A complete SEO solution for WordPress. Includes on-page optimization, sitemaps, backlink tracking, and social sharing tools.',
  icon: 'https://images.unsplash.com/photo-1432888622747-4eb9a8f2c20e?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '11.2 MB',
  driveFileId: '1PAQMz8nDm7dPiyUzCmnu1UybcrXfiREA',
  tags: ['seo', 'marketing', 'optimization'],
},
{
  id: 'wp-zuper-radio-player',
  name: 'Zuper Radio Player',
  slug: 'zuper-shoutcast-icecast-radio-player',
  category: 'wordpress-plugin',
  description:
    'A professional Shoutcast and Icecast radio player for WordPress. Features include stream history, current song display, and artist images.',
  icon: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.5 MB',
  driveFileId: '1jLXUBykjxurew1OqqbgKavKN4hwamNQZ',
  tags: ['plugin', 'radio', 'shoutcast', 'audio'],
} ,
{
  id: 'wp-yt-vimeo-slider',
  name: 'Youtube Vimeo Video Player',
  slug: 'youtube-vimeo-video-player-slider-wp',
  category: 'wordpress-plugin',
  description:
    'A versatile slider and player for YouTube and Vimeo videos. Supports playlists, touch swipe, and multiple layout options.',
  icon: 'https://images.unsplash.com/photo-1524169358666-79f22534bc6e?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '4.2 MB',
  driveFileId: '169v8cG4f7Hmu1VaehXy5If_E4am2Rh0Q',
  tags: ['plugin', 'video', 'slider', 'youtube'],
},
{
  id: 'wp-xpromoter-topbar',
  name: 'xPromoter',
  slug: 'xpromoter-top-bar-switcher-wp',
  category: 'wordpress-plugin',
  description:
    'A responsive top bar plugin to display promotions, announcements, or notifications. Includes a unique switcher for multiple messages.',
  icon: 'https://images.unsplash.com/photo-1502355984994-812f711096ac?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.8 MB',
  driveFileId: '1GNKSCKFo6SyU7uVq0u-7DUbxLpET8AID',
  tags: ['plugin', 'marketing', 'notification-bar'],
},
{
  id: 'wp-logos-showcase',
  name: 'Logos Showcase',
  slug: 'wordpress-logos-showcase-grid-carousel',
  category: 'wordpress-plugin',
  description:
    'Display a list of clients, supporters, or partners logos in a clean grid or an automated carousel layout.',
  icon: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.4 MB',
  driveFileId: '1QS_gSSIPzfmVI50_L6UPncs00SD-eGUo',
  tags: ['plugin', 'logos', 'carousel', 'branding'],
},
{
  id: 'wp-fullscreen-video-bg',
  name: 'Video Player & BG',
  slug: 'video-player-fullscreen-background-wp',
  category: 'wordpress-plugin',
  description:
    'Create stunning full-screen video backgrounds for your website pages or specific sections with this powerful player.',
  icon: 'https://images.unsplash.com/photo-1492619339714-8c8397e6388a?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '5.1 MB',
  driveFileId: '1OZ6DZEOCBRdB0reNhdhVJstgXE4iGu5Q',
  tags: ['plugin', 'video-background', 'full-screen'],
},
{
  id: 'wp-universal-video-player',
  name: 'Universal Video Player',
  slug: 'universal-video-player-wp',
  category: 'wordpress-plugin',
  description:
    'A top-tier video player that supports self-hosted MP4, YouTube, and Vimeo with a customizable interface and skins.',
  icon: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '4.8 MB',
  driveFileId: '10BiA96jnFMQyBiDOxrRTPtWd9Y7qBh60',
  tags: ['plugin', 'video', 'html5', 'custom-player'],
},
{
  id: 'wp-uberslider-layer',
  name: 'UberSlider',
  slug: 'uberslider-layer-slider-wp',
  category: 'wordpress-plugin',
  description:
    'A multi-layer slider plugin allowing you to add text, images, and buttons over sliding backgrounds with custom animations.',
  icon: 'https://images.unsplash.com/photo-1454165833767-027ffea9e772?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '6.2 MB',
  driveFileId: '1cq7mrCcWQAal8o70n4KmTzyAbAjSqFLe',
  tags: ['plugin', 'slider', 'layers', 'animations'],
},
{
  id: 'wp-sticky-music-player',
  name: 'Sticky Music Player',
  slug: 'sticky-html5-music-player-wp',
  category: 'wordpress-plugin',
  description:
    'An audio player that stays fixed at the top or bottom of your page, providing continuous playback as users browse.',
  icon: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.9 MB',
  driveFileId: '1hDCJWYo1RHAGSvBfxS_i5lOSxMfnHnLQ',
  tags: ['plugin', 'audio', 'sticky', 'music'],
},
{
  id: 'wp-revolution-video-player',
  name: 'Revolution Video Player',
  slug: 'revolution-video-player-bottom-playlist',
  category: 'wordpress-plugin',
  description:
    'Feature-rich video player with a bottom-scrollable playlist. Supports advertisements and social sharing options.',
  icon: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '5.5 MB',
  driveFileId: '1RzXnF_EEMWPRsQIFhABupxnHQOO3x3c4',
  tags: ['plugin', 'video', 'playlist', 'marketing'],
},
{
  id: 'wp-zoom-slider',
  name: 'Zoom Slider',
  slug: 'responsive-zoom-in-out-slider-wp',
  category: 'wordpress-plugin',
  description:
    'A beautiful slider plugin that applies Ken Burns style zoom effects to your images for a cinematic feel.',
  icon: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.1 MB',
  driveFileId: '1Vk5ntvX01JeJnKm6XTAPCWz-pV9L-nZn',
  tags: ['plugin', 'slider', 'ken-burns', 'visual'],
},
{
  id: 'wp-audio-player-pro',
  name: 'Audio Player PRO',
  slug: 'responsive-html5-audio-player-pro-wp',
  category: 'wordpress-plugin',
  description:
    'A professional-grade audio player with custom skins, playlist support, and full mobile responsiveness.',
  icon: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.7 MB',
  driveFileId: '1KEw8OK4oNHBIYOVaDhwix4MgpWCWjIbD',
  tags: ['plugin', 'audio', 'pro', 'playlist'],
},
{
  id: 'wp-shoutcast-radio-player',
  name: 'Radio Player PRO',
  slug: 'radio-player-shoutcast-icecast-wp',
  category: 'wordpress-plugin',
  description:
    'High-performance radio player specifically optimized for Shoutcast and Icecast servers with metadata support.',
  icon: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.8 MB',
  driveFileId: '1Fipdt365Y9grIag_AviCvrb3qLZBFTfi',
  tags: ['plugin', 'radio', 'streaming', 'shoutcast'],
},
{
  id: 'wp-multimedia-carousel',
  name: 'Multimedia Carousel',
  slug: 'multimedia-responsive-carousel-wp',
  category: 'wordpress-plugin',
  description:
    'An all-in-one carousel that supports images, videos (YouTube/Vimeo), and HTML content in a 3D or flat layout.',
  icon: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '4.3 MB',
  driveFileId: '1Y0tvEP0DzMb8XcQVBkSHuV9RAKau6mr6',
  tags: ['plugin', 'carousel', 'multimedia', '3d'],
},
{
  id: 'wp-magic-slider',
  name: 'Magic Slider',
  slug: 'magic-responsive-slider-carousel-wp',
  category: 'wordpress-plugin',
  description:
    'A creative slider and carousel plugin with over 100 transition effects and multiple navigation styles.',
  icon: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.9 MB',
  driveFileId: '1i-frCSHImI8cSV6kEvVdyixD_AJxd9sV',
  tags: ['plugin', 'slider', 'carousel', 'effects'],
},
{
  id: 'wp-magic-xmas-card',
  name: 'Magic Christmas Card',
  slug: 'magic-christmas-card-animation',
  category: 'wordpress-plugin',
  description:
    'Add a festive touch to your site with an animated Christmas card. Features falling snow and holiday music.',
  icon: 'https://images.unsplash.com/photo-1543589077-47d81606c1ad?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.5 MB',
  driveFileId: '1zMM98_1zomUkt9VF1wxYIjuSVly7toni',
  tags: ['plugin', 'holiday', 'animation', 'christmas'],
},
{
  id: 'wp-infinito-css',
  name: 'INFINITO',
  slug: 'infinito-custom-css-wp',
  category: 'wordpress-plugin',
  description:
    'Easily inject custom CSS into specific pages, posts, or your entire website without modifying theme files.',
  icon: 'https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.2 MB',
  driveFileId: '1uVdhgODKdeGhkE-Z7_EtQzOslbj7z2xE',
  tags: ['plugin', 'css', 'development', 'customization'],
},
{
  id: 'wp-fullscreen-bg-pro',
  name: 'FullScreen Background',
  slug: 'image-video-fullscreen-background-wp',
  category: 'wordpress-plugin',
  description:
    'A professional plugin for setting high-res images or videos as full-screen backgrounds with overlay support.',
  icon: 'https://images.unsplash.com/photo-1493612276216-ee3925520721?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.3 MB',
  driveFileId: '1tt7AKiZo2Mvym1Q6AHPvadCvbIyAfqw7',
  tags: ['plugin', 'background', 'design', 'video'],
},
{
  id: 'wp-html5-video-player',
  name: 'HTML5 Video Player',
  slug: 'html5-video-player-wordpress-plugin',
  category: 'wordpress-plugin',
  description:
    'A simple yet powerful HTML5 player for self-hosted videos. Highly compatible with all modern browsers.',
  icon: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.1 MB',
  driveFileId: '1Wi7jlMT8tYTBOB8ZCT-rkaxdurtWdSXr',
  tags: ['plugin', 'video', 'html5', 'player'],
},
{
  id: 'wp-html5-audio-player',
  name: 'HTML5 Audio Player',
  slug: 'html5-audio-player-wordpress-plugin',
  category: 'wordpress-plugin',
  description:
    'A lightweight and responsive audio player for MP3 and OGG files. Easy to embed using shortcodes.',
  icon: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.7 MB',
  driveFileId: '1vLE_cbudwnObmN-IyW4N4WVW1CbphPxi',
  tags: ['plugin', 'audio', 'music', 'player'],
},
{
  id: 'wp-famous-grid',
  name: 'Famous Gallery',
  slug: 'famous-responsive-grid-gallery-wp',
  category: 'wordpress-plugin',
  description:
    'Create a stunning grid of images and videos. Features a lightbox, social sharing, and infinite scroll options.',
  icon: 'https://images.unsplash.com/photo-1554147090-e11d63561a51?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.6 MB',
  driveFileId: '18XKBNd4faeyg9K9rTCQzcQQ-vN4wesdW',
  tags: ['plugin', 'gallery', 'grid', 'video'],
},
{
  id: 'wp-eventozilla',
  name: 'EventoZilla',
  slug: 'eventozilla-event-calendar-wp',
  category: 'wordpress-plugin',
  description:
    'Manage and display your events in a beautiful calendar view. Includes event categories and details pages.',
  icon: 'https://images.unsplash.com/photo-1506784365847-bbad939e9335?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '4.5 MB',
  driveFileId: '1Z5NsWA-B1FgOs48hsGjflbqBHO1Y7_F_',
  tags: ['plugin', 'events', 'calendar', 'management'],
},
{
  id: 'wp-countdown-pro',
  name: 'CountDown Pro',
  slug: 'countdown-pro-wp-plugin',
  category: 'wordpress-plugin',
  description:
    'Add stylish countdown timers to your site. Perfect for product launches, sales, or event announcements.',
  icon: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '1.9 MB',
  driveFileId: '1lKvoj1Av4KdiGAf_zsDDGNWuGTJfC-VZ',
  tags: ['plugin', 'timer', 'marketing', 'sales'],
},
{
  id: 'wp-clever-radio',
  name: 'CLEVER Radio',
  slug: 'clever-html5-radio-player-history',
  category: 'wordpress-plugin',
  description:
    'A smart radio player for Shoutcast/Icecast with automatic stream reconnection and detailed song history.',
  icon: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.2 MB',
  driveFileId: '1OscRe3kaA3Vxy9Bu9aC7S6DC1DObuYBB',
  tags: ['plugin', 'radio', 'shoutcast', 'history'],
},
{
  id: 'wp-chronos-countdown',
  name: 'Chronos CountDown',
  slug: 'chronos-countdown-wp',
  category: 'wordpress-plugin',
  description:
    'A highly customizable countdown timer with multiple themes and an integrated flip-clock animation style.',
  icon: 'https://images.unsplash.com/photo-1516733725897-1aa73b87c8e8?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '2.3 MB',
  driveFileId: '10hwBGjL8430E02BeU94879gcqM3lC7k8',
  tags: ['plugin', 'timer', 'countdown', 'clock'],
},
{
  id: 'wp-apollo-player',
  name: 'Apollo',
  slug: 'apollo-sticky-fullwidth-audio-player',
  category: 'wordpress-plugin',
  description:
    'A full-width sticky audio player with a sleek, minimalist design and seamless stream switching.',
  icon: 'https://images.unsplash.com/photo-1510915228340-29c85a43dcfe?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.4 MB',
  driveFileId: '1v70Pa-pB0lVoT8-IO86wkbPZdGgXU4Lt',
  tags: ['plugin', 'audio', 'sticky', 'player'],
},
{
  id: 'wp-all-in-one-slider',
  name: 'All In One Slider',
  slug: 'all-in-one-slider-responsive-wp',
  category: 'wordpress-plugin',
  description:
    'A complete slider solution featuring thumbnails, banners, and carousels with multiple transition effects.',
  icon: 'https://images.unsplash.com/photo-1481487196290-c152efe083f5?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '4.7 MB',
  driveFileId: '1MvNLuUS4Fb7xuUmNsrwam2kablGsBfS9',
  tags: ['plugin', 'slider', 'banner', 'responsive'],
},
{
  id: 'wp-accordion-slider-pro',
  name: 'Accordion Slider PRO',
  slug: 'accordion-slider-pro-responsive-wp',
  category: 'wordpress-plugin',
  description:
    'A unique accordion-style slider for images and videos that expands sections on hover or click.',
  icon: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=640&q=80',
  version: 'Latest',
  fileSize: '3.6 MB',
  driveFileId: '1Aa2ZSlz0ieTzWmYn6yOLJgke7qQ6-Z5o',
  tags: ['plugin', 'slider', 'accordion', 'video'],
},




]

/** Full catalog (Shopify themes + WP themes + WP plugins) */
export const STORE_ITEMS: StoreItem[] = [
  ...SHOPIFY_THEMES,
  ...WORDPRESS_THEMES,
  ...WORDPRESS_PLUGINS,
]

export function countByCategory(items: StoreItem[]) {
  return {
    shopify: items.filter((i) => i.category === 'shopify-theme').length,
    wpThemes: items.filter((i) => i.category === 'wordpress-theme').length,
    wpPlugins: items.filter((i) => i.category === 'wordpress-plugin').length,
  }
}

export function isIconImageUrl(icon: string): boolean {
  return icon.startsWith('http://') || icon.startsWith('https://')
}
