/** Local raster paths → WebP (generated by scripts/prepare-public-assets.mjs at build). */

export function toWebpSrc(src: string): string {
  if (!src || /^https?:\/\//i.test(src) || /\.(webp|svg|gif)$/i.test(src)) {
    return src
  }
  return src.replace(/\.(png|jpe?g)$/i, '.webp')
}

export function portfolioScreenshotAlt(projectTitle: string): string {
  return `${projectTitle} — custom web development Lahore Pakistan | RathiSoft portfolio`
}

export function caseStudyPreviewAlt(projectTitle: string): string {
  return `${projectTitle} website screenshot — web development case study | RathiSoft Lahore`
}

export function teamMemberAlt(name: string, role: string): string {
  return `${name}, ${role} — RathiSoft software development team Lahore Pakistan`
}

export function logoAlt(variant: 'mark' | 'wordmark' | 'about' = 'mark'): string {
  if (variant === 'wordmark') return 'RathiSoft wordmark — IT company Lahore Pakistan'
  if (variant === 'about') {
    return 'RathiSoft logo — custom web app development Lahore Pakistan'
  }
  return 'RathiSoft logo — web development agency Lahore Pakistan'
}
